from playwright.sync_api import sync_playwright
from pathlib import Path
import json,time,math

out=Path(__file__).resolve().parent;results=[];errors=[]
def check(name,condition,detail=None):
    results.append({'check':name,'passed':bool(condition),'detail':detail})
    print(('PASS ' if condition else 'FAIL ')+name+((' '+str(detail)) if detail is not None else ''),flush=True)
    if not condition:raise AssertionError(name+': '+str(detail))
def xy(page,x,z):
    return page.evaluate('p=>{const s=document.getElementById("plan"),pt=s.createSVGPoint();pt.x=p[0];pt.y=p[1];const a=pt.matrixTransform(s.getScreenCTM());return {x:a.x,y:a.y}}',[x,z])
def click_plan(page,x,z):
    p=xy(page,x,z);page.mouse.click(p['x'],p['y'])
def drag_plan(page,x,z,nx,nz):
    a=xy(page,x,z);b=xy(page,nx,nz);page.mouse.move(a['x'],a['y']);page.mouse.down();page.mouse.move(b['x'],b['y'],steps=8);page.mouse.up()
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True,args=['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage'])
    ctx=browser.new_context(viewport={'width':1440,'height':1000},accept_downloads=True)
    page=ctx.new_page();page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto('http://127.0.0.1:8774/codex-work/house-plan.html');page.wait_for_function('!!window.houseApp')
    check('본채 치수·초기 가구 배치',page.evaluate('houseApp.design.width===8000&&houseApp.design.depth===4500&&houseApp.design.furniture.every(f=>HouseKit.positionOK(houseApp.design,f))'))
    check('1층 본채 순면적 32.815m²',abs(page.evaluate('HouseKit.roomRegions({...houseApp.design,rear:false},"f1").reduce((a,r)=>a+r.area,0)')-32.815)<.0001)
    drag_plan(page,1550,2650,2050,2590)
    pos=page.evaluate('houseApp.design.furniture.find(f=>f.id==="coffee")')
    check('실제 포인터로 가구 이동',abs(pos['x']-2050)<25 and abs(pos['z']-2590)<25,pos)
    page.keyboard.press('r');check('R로 가구 15° 회전',page.evaluate('houseApp.design.furniture.find(f=>f.id==="coffee").r===15'))
    page.locator('#fHeight').fill('520');page.locator('#fHeight').press('Tab')
    check('가구 높이 치수 변경',page.evaluate('houseApp.design.furniture.find(f=>f.id==="coffee").h===520'))
    page.click('#undo');check('실행 취소',page.evaluate('houseApp.design.furniture.find(f=>f.id==="coffee").h===380'))
    page.click('#redo');check('다시 실행',page.evaluate('houseApp.design.furniture.find(f=>f.id==="coffee").h===520'))
    click_plan(page,2050,2590);handle=page.locator('[data-resize="coffee"]').bounding_box();page.mouse.move(handle['x']+handle['width']/2,handle['y']+handle['height']/2);page.mouse.down();page.mouse.move(handle['x']+handle['width']/2+18,handle['y']+handle['height']/2+10,steps=5);page.mouse.up()
    check('모서리 핸들로 크기 조절',page.evaluate('houseApp.design.furniture.find(f=>f.id==="coffee").w>950'))
    f=page.evaluate('houseApp.design.furniture.find(f=>f.id==="coffee")');extent=page.evaluate('HouseKit.extent(houseApp.design.furniture.find(f=>f.id==="coffee"))')
    drag_plan(page,f['x'],f['z'],100+extent['x']+35,2600)
    gap=page.evaluate('(()=>{const f=houseApp.design.furniture.find(f=>f.id==="coffee");return f.x-HouseKit.extent(f).x-100})()')
    check('벽 근처 자동 맞춤 2mm',abs(gap-2)<2,gap)
    page.click('#measureTool');click_plan(page,2700,2300);click_plan(page,3700,2300)
    check('두 점 측정 1000mm',page.evaluate('Math.abs(houseApp.design.measurements.at(-1).b.x-houseApp.design.measurements.at(-1).a.x)===1000'))
    page.click('#selectTool');page.click('[data-room-select="living"]');page.click('[data-finish="stone"]')
    check('방 바닥재 변경',page.evaluate('houseApp.design.finishes.living==="stone"'))
    click_plan(page,7600,4450);before=page.evaluate('houseApp.design.walls.length');page.keyboard.press('Delete')
    check('구조 보호벽 철거 잠금',page.evaluate('document.getElementById("selectionKind").textContent.includes("구조 보호")&&houseApp.design.walls.length')==before)
    click_plan(page,4900,2800);page.locator('#wallAt').fill('5200');page.locator('#wallAt').press('Tab')
    r=page.evaluate('HouseKit.roomRegions(houseApp.design,"f1").filter(r=>["living","bedroom","bath"].includes(r.id)).map(r=>({id:r.id,area:r.area}))')
    check('가벽 이동·접합 유지·면적 갱신',len(r)==3 and any(x['id']=='bedroom' and abs(x['area']-7.685)<.001 for x in r),r)
    page.click('#demolishWall');check('비내력벽 철거·공간 합산',not page.evaluate('houseApp.design.walls.some(w=>w.id==="partition-room")') and len(page.evaluate('HouseKit.roomRegions(houseApp.design,"f1").filter(r=>r.cells.some(c=>c.z>=100))'))==1)
    page.click('#undo');check('철거 취소',page.evaluate('houseApp.design.walls.some(w=>w.id==="partition-room")'))
    page.click('#wallTool');click_plan(page,3300,1700);click_plan(page,3300,2950);check('두 점 가벽 추가',page.evaluate('houseApp.design.walls.length===5'))
    page.click('#undo');page.click('#selectTool')
    with page.expect_download() as dl:page.click('#export')
    download=dl.value;download.save_as(str(out/'qa-plan-export.png'));check('2D PNG 내보내기',download.suggested_filename.endswith('.png') and (out/'qa-plan-export.png').stat().st_size>10000)
    page.click('#save');page.wait_for_timeout(400);saved=page.evaluate('JSON.parse(localStorage.getItem(HouseKit.KEY))');page.reload();page.wait_for_function('!!window.houseApp');check('새로고침 후 로컬 저장 복원',page.evaluate('houseApp.design')==saved)
    page.click('[data-view="3d"]');page.wait_for_function('!!houseApp.three',timeout=45000);page.wait_for_timeout(500)
    check('완성 집 외장·지붕 기본 표시',page.evaluate('houseApp.three.model.groups.roof.visible&&houseApp.three.model.groups.shell.visible'))
    check('편집한 높이·좌표의 실제 3D 연결',page.evaluate('(()=>{const f=houseApp.design.furniture.find(f=>f.id==="coffee"),o=houseApp.three.model.root.getObjectByName("coffee");return Math.abs(o.position.x-f.x/1000)<.0001&&Math.abs(o.position.z-f.z/1000)<.0001})()'))
    page.check('#cutaway');check('지붕 열기',page.evaluate('!houseApp.three.model.groups.roof.visible&&!houseApp.three.model.groups.upperShell.visible'))
    page.screenshot(path=str(out/'house-cutaway.png'))
    page.click('[data-floor="attic"]');page.click('#walkBtn');check('다락 둘러보기 +2300mm 오프셋',abs(page.evaluate('houseApp.three.camera.position.y')-3.65)<.001)
    check('다락 보이드 충돌 차단',page.evaluate('!HouseKit.walkAllowed(houseApp.design,"attic",2000,2200)'))
    # Exercise the actual navigation path from the bottom stair tread through the upper landing.
    page.click('#orbitBtn');page.click('[data-floor="f1"]');page.click('#walkBtn')
    ascent=page.evaluate('(()=>{const t=houseApp.three;t.camera.position.set(3.75,1.6,4.2);t.yaw=0;t.keys.add("w");for(let i=0;i<70;i++)walkTick(.04);t.keys.clear();return{floor:houseApp.floor,y:t.camera.position.y,z:t.camera.position.z}})()')
    check('실제 이동 함수로 1층 → 다락 계단 연결',ascent['floor']=='attic' and abs(ascent['y']-3.65)<.01 and ascent['z']<1.2,ascent)
    descent=page.evaluate('(()=>{const t=houseApp.three;t.yaw=Math.PI;t.keys.add("w");for(let i=0;i<70;i++)walkTick(.04);t.keys.clear();return{floor:houseApp.floor,y:t.camera.position.y,z:t.camera.position.z}})()')
    check('다락 → 1층 계단 하강',descent['floor']=='f1' and descent['z']>4.0,descent)
    page.click('#orbitBtn');page.click('[data-view="2d"]')
    site=ctx.new_page();site.on('pageerror',lambda e:errors.append(str(e)));site.goto('http://127.0.0.1:8774/codex-work/site-sim.html');site.wait_for_function('!!siteApp.app&&!!siteApp.app.model',timeout=45000);site.wait_for_timeout(400)
    check('현재 현장 기본 단계 3',site.evaluate('siteApp.stage===3&&siteApp.app.model.groups.f1Frame.visible&&siteApp.app.model.groups.atticFrame.visible&&!siteApp.app.model.groups.shell.visible'))
    check('동향 정면·기초 평행 축',site.evaluate('Math.abs(siteApp.app.model.root.rotation.y-Math.PI/2)<.0001'))
    check('설계 페이지 저장안의 현장 연결',site.evaluate('siteApp.design')==saved)
    for n in range(7):
        site.click(f'[data-stage="{n}"]');site.wait_for_timeout(1250)
        check(f'공사 {n}단계 전환',site.evaluate('siteApp.stage')==n)
    check('완공 창호·내부·증축·조경',site.evaluate('siteApp.app.model.groups.glazing.visible&&siteApp.app.model.groups.interior.visible&&siteApp.app.model.groups.extension.visible&&siteApp.app.landscape.visible'))
    site.screenshot(timeout=60000,path=str(out/'site-completed.png'))
    site.locator('#timeSlider').fill('18.5');sun=site.evaluate('({y:siteApp.app.sun.position.y,color:siteApp.app.sun.color.toArray()})');site.locator('#timeSlider').fill('12');noon=site.evaluate('siteApp.app.sun.position.y');check('시간대 태양 고도·색상 변화',sun['y']<noon and sun['color'][2]<sun['color'][0],sun)
    site.click('[data-yard="concrete"]');check('마당 비교안',site.evaluate('siteApp.app.yards.concrete.visible&&!siteApp.app.yards.grass.visible'))
    site.click('[data-yard="mixed"]');site.click('#currentStage');site.wait_for_timeout(1300);site.check('#landscapeToggle');check('현재 공사에 조경 미리보기',site.evaluate('siteApp.stage===3&&siteApp.app.landscape.visible'));site.uncheck('#landscapeToggle')
    site.click('#cinematic');site.wait_for_function('siteApp.stage!==0',timeout=20000);check('순항 단계 자동 진행',site.evaluate('siteApp.playing&&siteApp.stage>0'));site.click('#cinematic');check('순항 멈춤',site.evaluate('!siteApp.playing'))
    site.click('#walk');pos=site.evaluate('siteApp.app.camera.position.toArray()');site.keyboard.down('w');site.wait_for_function('siteApp.app.camera.position.x<4.8',timeout=20000);site.keyboard.up('w');newpos=site.evaluate('siteApp.app.camera.position.toArray()');check('현장 1인칭 키보드 이동',math.dist(pos,newpos)>.1,(pos,newpos));site.keyboard.press('Escape')
    check('현장 1인칭 종료',site.evaluate('!siteApp.app.walk'))
    site.click('#currentStage');site.wait_for_timeout(1300);site.screenshot(timeout=60000,path=str(out/'site-current.png'))
    # Cross-tab storage event updates the constructed model without a reload.
    page.bring_to_front();click_plan(page,6000,3900);page.click('[data-room-select="living"]');page.click('[data-finish="concrete"]');page.click('#save');page.wait_for_timeout(400)
    site.wait_for_function('siteApp.design.finishes.living==="concrete"');check('탭 간 실시간 저장안 반영',site.evaluate('siteApp.design.finishes.living==="concrete"'))
    check('데스크톱 가로 넘침 없음',page.evaluate('document.documentElement.scrollWidth<=innerWidth') and site.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    check('자바스크립트 실행 오류 없음',not errors,errors)
    page.close();site.close()
    # A touch viewport exercises the same artifact rather than a separate mobile UI.
    mobile=browser.new_context(viewport={'width':390,'height':844},device_scale_factor=1,is_mobile=True,has_touch=True)
    mp=mobile.new_page();mp.on('pageerror',lambda e:errors.append(str(e)));mp.goto('http://127.0.0.1:8774/codex-work/house-plan.html');mp.wait_for_function('!!window.houseApp')
    check('390px 모바일 평면 가로 넘침 없음',mp.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    mp.locator('[data-floor="attic"]').tap();check('모바일 층 전환',mp.evaluate('houseApp.floor==="attic"'));mp.locator('[data-floor="f1"]').tap();mp.screenshot(path=str(out/'house-mobile.png'),full_page=True)
    mp.goto('http://127.0.0.1:8774/codex-work/site-sim.html');mp.wait_for_function('!!siteApp.app&&!!siteApp.app.model',timeout=45000);check('390px 모바일 현장 가로 넘침 없음',mp.evaluate('document.documentElement.scrollWidth<=innerWidth'));mp.locator('[data-stage="6"]').tap();mp.wait_for_timeout(1500);check('모바일 단계 터치 전환',mp.evaluate('siteApp.stage===6'));mp.screenshot(path=str(out/'site-mobile.png'),full_page=True)
    mp.locator('#walk').tap();check('모바일 1인칭 이동 패드',mp.locator('#walkPad').is_visible());mp.locator('#orbit').tap();mobile.close()
    # CDN failure leaves the 2D artifact usable and provides a recovery path for both pages.
    offline=browser.new_context(viewport={'width':1200,'height':900});offline.route('https://cdn.jsdelivr.net/**',lambda route:route.abort());op=offline.new_page();op.goto('http://127.0.0.1:8774/codex-work/house-plan.html');op.click('[data-view="3d"]');op.wait_for_function('!document.getElementById("threeError").hidden');op.click('#back2d');check('CDN 실패 후 2D 복구',op.evaluate('houseApp.view==="2d"&&document.getElementById("plan").childElementCount>0'));op.goto('http://127.0.0.1:8774/codex-work/site-sim.html');op.wait_for_function('!document.getElementById("siteError").hidden');check('CDN 실패 현장 안내',op.locator('#retry').is_visible());offline.close()
    browser.close()
(out/'qa-results.json').write_text(json.dumps({'checks':results,'errors':errors},ensure_ascii=False,indent=2))
print('ALL',len(results),'checks passed',flush=True)
