from playwright.sync_api import sync_playwright
from pathlib import Path
import json,hashlib
out=Path(__file__).resolve().parent;records=[];errors=[]
def check(name,ok,detail=None):
 records.append({'check':name,'passed':bool(ok),'detail':detail});print(('PASS ' if ok else 'FAIL ')+name+' '+str(detail),flush=True)
 if not ok:raise AssertionError(name)
with sync_playwright() as p:
 b=p.chromium.launch(headless=True,args=['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage'])
 c=b.new_context(viewport={'width':1440,'height':1000});page=c.new_page();page.on('pageerror',lambda e:errors.append(str(e)));page.goto('http://127.0.0.1:8774/codex-work/house-plan.html');page.wait_for_function('!!houseApp')
 bad=page.evaluate('houseApp.design.furniture.filter(f=>!HouseKit.positionOK(houseApp.design,f)).map(f=>f.id)');check('수정된 기본 가구의 벽·계단·보이드 간섭 없음',not bad,bad);check('증축 외벽 실치수 3000 × 3300mm',page.evaluate('(()=>{const w=HouseKit.external(houseApp.design,"attic");return w.find(x=>x.id==="extra-front").at+50===3300&&w.find(x=>x.id==="extra-right").at+50-8000===3000})()'));page.screenshot(timeout=60000,path=str(out/'house-2d.png'))
 page.click('[data-view="3d"]');page.wait_for_function('!!houseApp.three',timeout=45000);page.check('#cutaway');page.wait_for_function('!houseApp.three.dirty',timeout=45000)
 geometry=page.evaluate('(()=>{const{T,model}=houseApp.three;model.root.updateMatrixWorld(true);const ray=new T.Raycaster(),visible=h=>{for(let o=h.object;o;o=o.parent)if(!o.visible)return false;return true};ray.set(new T.Vector3(2.9,10,3),new T.Vector3(0,-1,0));const hole=ray.intersectObject(model.root,true).filter(visible)[0]?.point.y;ray.set(new T.Vector3(3.75,2.8,1.4),new T.Vector3(0,0,-1));ray.far=.5;return{voidTop:hole,landingBarrier:ray.intersectObject(model.root,true).filter(visible).length}})()')
 check('보이드 바닥 구멍·계단 상부 난간 출입 틈',geometry['voidTop']<.03 and geometry['landingBarrier']==0,geometry);page.screenshot(timeout=60000,path=str(out/'house-cutaway.png'));page.uncheck('#cutaway');page.wait_for_function('!houseApp.three.dirty',timeout=45000);page.screenshot(timeout=60000,path=str(out/'house-3d.png'));page.click('#walkBtn')
 route=page.evaluate('(()=>{const t=houseApp.three;t.camera.position.set(2.9,1.6,.95);const reached=[];for(const target of [[4.55,.95],[4.55,.9],[5.1,.9],[6.8,.9],[4.55,.9],[4.55,2.2],[5.1,2.2],[5.85,2.4],[5.85,3.7],[5.85,4.25],[7,4.25]]){let n=0;while(n++<800){const dx=target[0]-t.camera.position.x,dz=target[1]-t.camera.position.z;if(Math.hypot(dx,dz)<.02)break;t.yaw=Math.atan2(-dx,-dz);t.keys.add("w");walkTick(.01);}t.keys.clear();reached.push({target,at:[t.camera.position.x,t.camera.position.z],floor:houseApp.floor,ok:Math.hypot(target[0]-t.camera.position.x,target[1]-t.camera.position.z)<.025});}return reached})()')
 check('실제 충돌 함수로 거실 → 욕실 → 침실 이동',all(r['ok'] and r['floor']=='f1' for r in route),route)
 ascent=page.evaluate('(()=>{const t=houseApp.three;t.camera.position.set(3.75,1.6,4.2);t.yaw=0;t.keys.add("w");for(let i=0;i<70;i++)walkTick(.04);t.keys.clear();return{floor:houseApp.floor,y:t.camera.position.y,z:t.camera.position.z}})()');check('새 계단으로 다락 상승',ascent['floor']=='attic' and abs(ascent['y']-3.65)<.01 and ascent['z']<1.2,ascent)
 descent=page.evaluate('(()=>{const t=houseApp.three;t.yaw=Math.PI;t.keys.add("w");for(let i=0;i<70;i++)walkTick(.04);t.keys.clear();return{floor:houseApp.floor,y:t.camera.position.y,z:t.camera.position.z}})()');check('계단 하강·낮은 첫 단 연결',descent['floor']=='f1' and descent['y']<1.7 and descent['z']>4.1,descent);page.click('#orbitBtn');page.click('[data-view="2d"]');page.close()
 sp=c.new_page();sp.on('pageerror',lambda e:errors.append(str(e)));sp.goto('http://127.0.0.1:8774/codex-work/site-sim.html');sp.wait_for_function('!!siteApp.app&&!!siteApp.app.model',timeout=45000);sp.wait_for_function('!siteApp.app.dirty',timeout=45000);sp.screenshot(timeout=60000,path=str(out/'site-current.png'));sp.click('[data-stage="6"]');sp.wait_for_function('transition===null&&!siteApp.app.dirty',timeout=45000);sp.wait_for_function('!siteApp.app.dirty',timeout=45000);sp.screenshot(timeout=60000,path=str(out/'site-completed.png'));sp.click('#walk')
 siteStair=sp.evaluate('(()=>{siteApp.app.camera.position.set(-.05,2.5,.25);siteApp.app.yaw=Math.PI/2;siteApp.app.keys.add("w");for(let i=0;i<90;i++)walkTick(.03);siteApp.app.keys.clear();return{floor:siteApp.app.floor,y:siteApp.app.camera.position.y,x:siteApp.app.camera.position.x}})()');check('현장 완공 모델의 다락 높이·계단 연결',siteStair['floor']=='attic' and abs(siteStair['y']-4.55)<.01,siteStair);sp.click('#orbit');sp.close()
 mobile=b.new_context(viewport={'width':390,'height':844},is_mobile=True,has_touch=True);mp=mobile.new_page();mp.on('pageerror',lambda e:errors.append(str(e)));mp.goto('http://127.0.0.1:8774/codex-work/house-plan.html');mp.wait_for_function('!!houseApp');mp.screenshot(timeout=60000,path=str(out/'house-mobile.png'),full_page=True);check('최종 모바일 가구 메뉴·가로 배치',mp.evaluate('document.documentElement.scrollWidth<=innerWidth&&[...document.querySelectorAll("#library button")].every(b=>b.getBoundingClientRect().width>=48)'));mp.goto('http://127.0.0.1:8774/codex-work/site-sim.html');mp.wait_for_function('!!siteApp.app&&!!siteApp.app.model',timeout=45000);mp.locator('[data-stage="6"]').tap();mp.wait_for_function('transition===null&&!siteApp.app.dirty',timeout=45000);mp.screenshot(timeout=60000,path=str(out/'site-mobile.png'),full_page=True);check('최종 모바일 현장',mp.evaluate('siteApp.stage===6&&document.documentElement.scrollWidth<=innerWidth'));check('최종 수정의 실행 오류 없음',not errors,errors);b.close()
files=Path('/home/ancom/workspace/10pyeong-house/codex-work')
(out/'qa-routes.json').write_text(json.dumps({'checks':records,'errors':errors,'sha256':{n:hashlib.sha256((files/n).read_bytes()).hexdigest() for n in ['house-plan.html','site-sim.html']}},ensure_ascii=False,indent=2))
