(()=>{
 const D=window.Design,$=id=>document.getElementById(id),svg=$('plan-svg');let state=D.readDesign(),floor=0,mode='2d',selected=null,tool='select',measurement=[],hoverPoint=null,drag=null,undo=[],redo=[],viewer=null,cut=false,zoom=1,pan={x:0,z:0},saveTimer,roomChoice='',viewPending=false;
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const fmt=n=>Math.round(n*1000).toLocaleString('ko-KR'),text=(x,y,s,size=125,color='#5d6e5d',extra='')=>`<text x="${x*1000}" y="${y*1000}" font-family="Arial,sans-serif" font-size="${size}" fill="${color}" text-anchor="middle" ${extra}>${esc(s)}</text>`;
 function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(saveTimer);saveTimer=setTimeout(()=>$('toast').classList.remove('show'),2400);}
 function store(){try{localStorage.setItem(D.STORAGE_KEY,JSON.stringify(state));$('save-status').textContent='저장됨 · '+new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})+' · 현장 페이지와 공유';return true;}catch{$('save-status').textContent='이 브라우저에서 로컬 저장을 사용할 수 없습니다.';return false;}}
 function history(before){if(JSON.stringify(before)===JSON.stringify(state))return;undo.push(before);if(undo.length>60)undo.shift();redo=[];store();$('undo').disabled=!undo.length;$('redo').disabled=!redo.length;}
 function change(fn){const before=D.clone(state);fn();history(before);draw();properties();update3D();}
 function syncOptions(){$('rear-option').checked=state.rear;$('extension-option').checked=state.extension;$('mobile-rear-option').checked=state.rear;$('mobile-extension-option').checked=state.extension;}
 function dim(x1,z1,x2,z2,label){const nx=z1===z2?0:.11,nz=z1===z2?.11:0;return `<g stroke="#879180" stroke-width="12" fill="none"><line x1="${x1*1000}" y1="${z1*1000}" x2="${x2*1000}" y2="${z2*1000}"/><line x1="${(x1-nx-nz)*1000}" y1="${(z1-nz-nx)*1000}" x2="${(x1+nx+nz)*1000}" y2="${(z1+nz+nx)*1000}"/><line x1="${(x2-nx-nz)*1000}" y1="${(z2-nz-nx)*1000}" x2="${(x2+nx+nz)*1000}" y2="${(z2+nz+nx)*1000}"/></g>`+text((x1+x2)/2+(z1!==z2?-.16:0),(z1+z2)/2+(z1===z2?-.15:0),label,140,'#60705d',z1!==z2?`transform="rotate(-90 ${(x1-.16)*1000} ${(z1+z2)/2*1000})"`:'');}
 function openingSVG(w,o){const hor=w.z1===w.z2,a=o.at,x=hor?a:w.x1,z=hor?w.z1:a,s=(hor?`translate(${x*1000},${z*1000})`:`translate(${x*1000},${z*1000}) rotate(90)`);if(o.wing&&!state.extension)return '';
  if(o.type==='window')return `<g transform="${s}" fill="#e8f4f1" stroke="#78a6a6" stroke-width="18"><rect x="0" y="-44" width="${o.w*1000}" height="88"/><path d="M0 0H${o.w*1000} M${o.w*500} -44V44"/></g>`;
  return `<g transform="${s}" stroke="#849781" stroke-width="14" fill="none"><rect x="0" y="-65" width="${o.w*1000}" height="130" fill="#fafbf6" stroke="none"/><path d="M0 0V${o.w*1000} M0 ${o.w*1000} A${o.w*1000} ${o.w*1000} 0 0 0 ${o.w*1000} 0"/></g>`+(o.label?text(x+(hor?o.w/2:-.27),z+(hor?-.2:o.w/2),o.label,115,'#7d603c'):'');
 }
 function draw(){const minZ=state.rear?0:3,maxX=state.extension&&floor===1?11:8,baseW=maxX+3.1,baseH=7.5-minZ+2.8,viewW=baseW*1000/zoom,viewH=baseH*1000/zoom;
  svg.setAttribute('viewBox',`${((maxX/2)-viewW/2000+pan.x)*1000} ${((minZ+7.5)/2-viewH/2000+pan.z)*1000} ${viewW} ${viewH}`);
  let out=`<defs><pattern id="grid" width="250" height="250" patternUnits="userSpaceOnUse"><circle cx="0" cy="0" r="6" fill="#dce1d2"/></pattern><pattern id="wood" width="850" height="180" patternUnits="userSpaceOnUse"><rect width="850" height="180" fill="#e8e1d0"/><path d="M0 0H850 M0 180H850 M0 0V180" fill="none" stroke="#d9cbb5" stroke-width="8"/></pattern><pattern id="tile" width="300" height="300" patternUnits="userSpaceOnUse"><rect width="300" height="300" fill="#e8ebe2"/><path d="M0 0H300V300H0Z" fill="none" stroke="#c8d0c0" stroke-width="8"/></pattern><pattern id="stone" width="400" height="300" patternUnits="userSpaceOnUse"><rect width="400" height="300" fill="#d9dad0"/><path d="M0 0H400V300H0Z" fill="none" stroke="#c3c6b7" stroke-width="10"/></pattern><pattern id="void" width="130" height="130" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="130" height="130" fill="#f5f6ed"/><line x1="0" y1="0" x2="0" y2="130" stroke="#dfe5d5" stroke-width="13"/></pattern></defs><rect x="-20000" y="-20000" width="50000" height="50000" fill="#fafbf6"/><rect x="-20000" y="-20000" width="50000" height="50000" fill="url(#grid)"/>`;
  const rooms=D.roomGeometry(state,floor);
  if(floor===1){out+=`<rect x="100" y="3100" width="4750" height="4300" fill="url(#void)"/>`+text(2.25,4.65,'VOID',205,'#91a181')+text(2.25,4.95,'거실 위 · 바닥 없음',130,'#91a181');}
  for(const room of rooms)for(const c of room.cells)out+=`<rect data-room="${esc(room.name)}" x="${c.x*1000}" y="${c.z*1000}" width="${c.w*1000}" height="${c.d*1000}" fill="url(#${D.materialFor(state,room)})"/>`;
  if(floor===0)out+=`<rect x="0" y="7550" width="8000" height="650" fill="#e6deca" stroke="#c2b496" stroke-width="10"/>`+text(1.1,7.96,'현관 데크',110,'#8c7758');
  for(const w of D.wallsFor(state,floor)){
   const chosen=selected?.type==='wall'&&selected.id===w.id,color=w.kind==='structure'?'#314a3b':chosen?'#bd713f':'#8b9d83';out+=`<line data-wall="${w.id}" x1="${w.x1*1000}" y1="${w.z1*1000}" x2="${w.x2*1000}" y2="${w.z2*1000}" stroke="${color}" stroke-width="${w.t*1000}"/><line data-wall="${w.id}" x1="${w.x1*1000}" y1="${w.z1*1000}" x2="${w.x2*1000}" y2="${w.z2*1000}" stroke="transparent" stroke-width="230"/>`;
   w.openings.forEach(o=>out+=openingSVG(w,o));
  }
  if(floor===1){for(const [a,b]of[[3.1,4.78],[5.6,7.4]])out+=`<path d="M4900 ${a*1000}V${b*1000}" stroke="#5d7c64" stroke-width="24"/>`;for(let z=3.1;z<7.4;z+=.14)if(z<4.78||z>5.6)out+=`<circle cx="4900" cy="${z*1000}" r="22" fill="#5d7c64"/>`;out+=text(4.42,3.9,'난간',100,'#5c795e');if(state.extension){out+=`<path d="M8000 3500H11000V6800H8000 M8000 3500V4250 M8000 5150V6800" stroke="#314a3b" stroke-width="100" fill="none"/>`+dim(8,7.95,11,7.95,'3,000')+dim(11.65,3.5,11.65,6.8,'3,300');}}
  out+=`<g stroke="#9f967e" stroke-width="14" fill="none"><rect x="3850" y="5050" width="1000" height="2200"/>`;
  for(let i=1;i<13;i++)out+=`<path d="M3850 ${5050+i*2200/13}H4850"/>`;
  out+=`<path d="M4350 7000V5280 M4230 5440L4350 5280L4470 5440" stroke="#768e72" stroke-width="24"/></g>`+text(4.34,7.08,floor===0?'UP':'DN',110,'#6c825f');
  for(const room of rooms){let x=room.cx,z=room.cz;if(room.name==='거실·주방'){x=2.2;z=4.8;}if(room.name==='침실'){x=6.4;z=5.1;}if(room.name==='다락'){x=6.4;z=4.65;}
   out+=`<g pointer-events="none">${text(x,z,room.name,room.name.length>14?110:145,'#576650')}${text(x,z+.23,`${room.area.toFixed(2)} m²`,115,'#88957d')}</g>`;
  }
  for(const f of D.furnitureFor(state,floor)){
   const chosen=selected?.type==='furniture'&&selected.id===f.id,stroke=chosen?'#b8713c':'#9a967e';out+=`<g data-furniture="${esc(f.id)}" transform="translate(${f.x*1000},${f.z*1000}) rotate(${f.r})" style="cursor:move"><rect x="${-f.w*500}" y="${-f.d*500}" width="${f.w*1000}" height="${f.d*1000}" rx="${f.type==='sofa'?70:20}" fill="${f.color}" stroke="${stroke}" stroke-width="${chosen?24:13}"/>`;
   if(f.type==='bed')out+=`<rect x="${-f.w*450}" y="${-f.d*450}" width="${f.w*900}" height="${Math.min(.4,f.d*.2)*1000}" rx="40" fill="#f6f4eb" stroke="#bcb5a2" stroke-width="8"/><path d="M${-f.w*500} ${-f.d*100}H${f.w*500}" stroke="#bcb5a2" stroke-width="12"/>`;
   if(f.type==='sofa')out+=`<rect x="${-f.w*500+65}" y="${-f.d*500+45}" width="${f.w*1000-130}" height="120" rx="30" fill="#91a08a"/><path d="M0 -${f.d*300}V${f.d*400}" stroke="#91a08a" stroke-width="10"/>`;
   if(f.type==='kitchen')out+=`<rect x="${-f.w*280}" y="-180" width="450" height="360" rx="30" fill="#929f93"/>`;
   out+=`<text text-anchor="middle" dominant-baseline="middle" font-family="Arial,sans-serif" font-size="105" fill="#535b48" style="pointer-events:none">${esc(f.label)}</text>`;
   if(chosen)out+=`<rect x="${-f.w*500-70}" y="${-f.d*500-70}" width="${f.w*1000+140}" height="${f.d*1000+140}" rx="20" fill="none" stroke="#b8713c" stroke-width="14" stroke-dasharray="35 25"/><line x1="0" y1="${-f.d*500-70}" x2="0" y2="${-f.d*500-290}" stroke="#b8713c" stroke-width="14"/><circle data-handle="rotate" cx="0" cy="${-f.d*500-290}" r="95" fill="#fffaf0" stroke="#b8713c" stroke-width="20"/><text x="0" y="${-f.d*500-253}" text-anchor="middle" font-size="125" fill="#b8713c" pointer-events="none">↻</text><circle data-handle="resize" cx="${f.w*500}" cy="${f.d*500}" r="95" fill="#b8713c" stroke="#fffaf0" stroke-width="20"/>`;
   out+='</g>';
  }
  out+=dim(0,minZ-.5,8,minZ-.5,'8,000 mm · 수정 폭')+dim(-.6,minZ,-.6,7.5,`${fmt(7.5-minZ)} mm`);
  if(state.rear&&floor===0){out+=dim(8.5,0,8.5,3,'3,000 · 증축안')+dim(8.5,3,8.5,7.5,'4,500 · 본체')+text(4,-.88,'볼펜 증축 스케치 반영 · 치수 일부 가정',108,'#9b7f59');}
  if(measurement.length){const a=measurement[0],b=measurement[1]||hoverPoint||a;out+=`<g stroke="#bd713f" stroke-width="20" fill="none"><path d="M${a.x*1000} ${a.z*1000}L${b.x*1000} ${b.z*1000}" stroke-dasharray="45 25"/><circle cx="${a.x*1000}" cy="${a.z*1000}" r="45"/><circle cx="${b.x*1000}" cy="${b.z*1000}" r="45"/></g>`+text((a.x+b.x)/2,(a.z+b.z)/2-.13,fmt(Math.hypot(b.x-a.x,b.z-a.z))+' mm',140,'#a85e32');}
  svg.innerHTML=out;$('floor-status').textContent=(floor?'다락 · 바닥 +2,300 mm':'1층 · 단위 mm')+(tool==='measure'?' · 두 점을 선택':'');
 }
 function properties(){const target=$('property-content');let content='';
  if(selected?.type==='furniture'){const f=state.furniture.find(f=>f.id===selected.id);if(!f){selected=null;return properties();}content=`<div class="eyebrow">SELECTED / 가구</div><h2 class="info-title">${esc(f.label)}</h2><p class="small-note">${floor?'다락 · 바닥 높이 +2,300 mm':'1층 · 바닥 높이 ±0 mm'}</p><div class="prop-grid"><label>너비 mm<input id="prop-w" type="number" min="200" max="3500" step="50" value="${Math.round(f.w*1000)}"></label><label>깊이 mm<input id="prop-d" type="number" min="200" max="3500" step="50" value="${Math.round(f.d*1000)}"></label><label>높이 mm<input id="prop-h" type="number" min="100" max="2200" step="50" value="${Math.round(f.h*1000)}"></label><label>회전 °<input id="prop-r" type="number" min="0" max="359" step="15" value="${Math.round((f.r+360)%360)}"></label></div><div class="prop-buttons"><button id="rotate-item">↻ 90° 회전</button><button id="delete-item" class="danger">가구 삭제</button></div><p class="small-note">x ${fmt(f.x)} / y ${fmt(f.z)} mm<br>이동 50mm: 방향키 · 회전: R</p>`;target.innerHTML=content;
   for(const key of['w','d','h','r'])$('prop-'+key).onchange=e=>{const n=Number(e.target.value);if(!Number.isFinite(n)||n<(key==='r'?0:100)||n>(key==='r'?359:key==='h'?2200:3500)){toast('치수를 허용 범위 안에서 입력하세요.');properties();return;}change(()=>{const old={...f};f[key]=key==='r'?n:n/1000;if(!place(f,false)){Object.assign(f,old);toast('벽 또는 바닥 구멍을 벗어나는 크기입니다.');}});};
   $('rotate-item').onclick=()=>change(()=>{const old={...f};f.r=(f.r+90)%360;if(!place(f,false))Object.assign(f,old);});$('delete-item').onclick=()=>change(()=>{state.furniture=state.furniture.filter(v=>v.id!==f.id);selected=null;});
  }else if(selected?.type==='wall'){const w=D.wallsFor(state,floor).find(w=>w.id===selected.id);if(!w){selected=null;return properties();}const locked=w.kind==='structure',hor=w.z1===w.z2;content=`<div class="eyebrow">SELECTED / 벽체</div><h2 class="info-title">${locked?'외곽 구조 프레임':'내부 칸막이'}</h2><p class="small-note">${locked?'보호 구조 · 편집 잠금':'두께 '+fmt(w.t)+' mm · 이동 및 철거 가능'}</p>${locked?'<div class="help-box">도면에 구조 계산이 없어 외곽 프레임을 보수적으로 잠갔습니다. 내부 칸막이는 공간 검토용으로 편집할 수 있습니다.</div>':`<div class="prop-grid"><label class="wide">${hor?'상하':'좌우'} 위치 mm<input id="wall-position" type="number" min="600" max="${hor?6800:7300}" step="50" value="${fmt(hor?w.z1:w.x1).replaceAll(',','')}"></label></div><button id="demolish" class="danger">이 칸막이 철거</button><p class="small-note">벽을 끌어도 위치가 바뀝니다.<br>철거 후 방 면적이 다시 계산됩니다.</p>`}`;target.innerHTML=content;
   if(!locked){$('wall-position').onchange=e=>change(()=>{const a=state.walls.find(v=>v.id===w.id),n=Math.max(.6,Math.min(hor?6.8:7.3,Number(e.target.value)/1000));if(hor)a.z1=a.z2=n;else a.x1=a.x2=n;});$('demolish').onclick=()=>change(()=>{state.walls.find(v=>v.id===w.id).active=false;selected=null;});}
  }else{const rooms=D.roomGeometry(state,floor);content=`<div class="eyebrow">${floor?'ATTIC':'FIRST FLOOR'} / 공간 정보</div><h2 class="info-title">${floor?'빛이 내려오는 다락':'생활을 담는 1층'}</h2><p class="small-note">${floor?'보이드를 통해 아래층을 바라봅니다.':'본체 8,000 × 4,500 mm'+(state.rear?' + 후면 증축안':'')}</p><div class="area-list">${rooms.map(r=>`<div class="area-row"><span>${esc(r.name)}</span><strong>${r.area.toFixed(2)} m²</strong></div>`).join('')}</div><div class="area-total"><span>벽 두께 제외 · ${floor?'보이드 제외':'실내 순면적'}</span><strong>${rooms.reduce((a,r)=>a+r.area,0).toFixed(2)}<small style="font-size:12px;letter-spacing:0"> m²</small></strong></div>${floor?'<div class="help-box">다락 경계는 1.1m 난간입니다. 증축안은 총 9.90 m², 벽 두께 제외 8.68 m²입니다.</div>':''}`;target.innerHTML=content;}
  const rooms=D.roomGeometry(state,floor),sel=$('room-select');if(!rooms.some(r=>r.name===roomChoice))roomChoice=rooms[0]?.name||'';sel.innerHTML=rooms.map(r=>`<option ${r.name===roomChoice?'selected':''} value="${esc(r.name)}">${esc(r.name)}</option>`).join('');const room=rooms.find(r=>r.name===roomChoice);document.querySelectorAll('[data-material]').forEach(b=>b.classList.toggle('active',room&&D.materialFor(state,room)===b.dataset.material));syncOptions();
 }
 function place(f,snap=true){const b=D.bounds(f),minZ=state.rear?.1:3.1;f.x=Math.max(.1+b.w/2,Math.min((f.floor&&state.extension?10.9:7.9)-b.w/2,f.x));f.z=Math.max((f.floor?3.1:minZ)+b.d/2,Math.min(7.4-b.d/2,f.z));
  if(snap)for(const w of D.wallsFor(state,f.floor)){const hor=w.z1===w.z2;if(hor){for(const side of[-1,1]){const desired=w.z1+side*(w.t/2+b.d/2);if(Math.abs(f.z-desired)<.16&&f.x>w.x1-b.w/2&&f.x<w.x2+b.w/2)f.z=desired;}}else for(const side of[-1,1]){const desired=w.x1+side*(w.t/2+b.w/2);if(Math.abs(f.x-desired)<.16&&f.z>w.z1-b.d/2&&f.z<w.z2+b.d/2)f.x=desired;}}
  const corners=[[-b.w/2,-b.d/2],[b.w/2,-b.d/2],[-b.w/2,b.d/2],[b.w/2,b.d/2]];return corners.every(([x,z])=>D.insideFloor(state,f.floor,f.x+x,f.z+z,-.001));
 }
 function point(e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const t=p.matrixTransform(svg.getScreenCTM().inverse());return {x:t.x/1000,z:t.y/1000};}
 svg.addEventListener('pointerdown',e=>{if(mode!=='2d')return;const p=point(e);if(tool==='measure'){measurement=measurement.length===1?[measurement[0],p]:[p];draw();return;}
  const furniture=e.target.closest('[data-furniture]'),wall=e.target.closest('[data-wall]'),handle=e.target.closest('[data-handle]');
  if(furniture){selected={type:'furniture',id:furniture.dataset.furniture};const f=state.furniture.find(f=>f.id===selected.id);drag={type:handle?.dataset.handle||'furniture',id:f.id,start:p,initial:{...f},before:D.clone(state)};}
  else if(wall){selected={type:'wall',id:wall.dataset.wall};const w=state.walls.find(v=>v.id===selected.id);if(w&&floor===0)drag={type:'wall',id:w.id,start:p,initial:{...w},before:D.clone(state)};}
  else{selected=null;drag={type:'pan',start:p,initial:{...pan},cx:e.clientX,cy:e.clientY};const room=e.target.closest('[data-room]');if(room)roomChoice=room.dataset.room;}
  svg.setPointerCapture(e.pointerId);draw();properties();});
 svg.addEventListener('pointermove',e=>{const p=point(e);if(tool==='measure'&&measurement.length===1){hoverPoint=p;draw();}if(!drag)return;
  if(drag.type==='pan'){const ct=svg.getScreenCTM(),dx=(e.clientX-drag.cx)/ct.a/1000,dz=(e.clientY-drag.cy)/ct.d/1000;pan.x=drag.initial.x-dx;pan.z=drag.initial.z-dz;draw();return;}
  if(drag.type==='wall'){const w=state.walls.find(v=>v.id===drag.id),hor=w.z1===w.z2,init=drag.initial;if(hor)w.z1=w.z2=Math.max(.6,Math.min(6.8,Math.round((init.z1+p.z-drag.start.z)*20)/20));else w.x1=w.x2=Math.max(.6,Math.min(7.3,Math.round((init.x1+p.x-drag.start.x)*20)/20));}
  else{const f=state.furniture.find(v=>v.id===drag.id),old={...f};if(drag.type==='rotate'){f.r=(Math.round((Math.atan2(p.z-f.z,p.x-f.x)*180/Math.PI+90)/15)*15+360)%360;}
   else if(drag.type==='resize'){const a=-f.r*Math.PI/180,dx=p.x-f.x,dz=p.z-f.z;f.w=Math.max(.2,Math.min(3.5,Math.round(Math.abs(dx*Math.cos(a)-dz*Math.sin(a))*40)/20));f.d=Math.max(.2,Math.min(3.5,Math.round(Math.abs(dx*Math.sin(a)+dz*Math.cos(a))*40)/20));}
   else{f.x=drag.initial.x+p.x-drag.start.x;f.z=drag.initial.z+p.z-drag.start.z;}if(!place(f,drag.type==='furniture'))Object.assign(f,old);}
  draw();update3D();});
 function endDrag(){if(!drag)return;if(drag.before)history(drag.before);drag=null;properties();update3D();}svg.addEventListener('pointerup',endDrag);svg.addEventListener('pointercancel',endDrag);
 svg.addEventListener('wheel',e=>{if(mode==='2d'){e.preventDefault();zoom=Math.max(.65,Math.min(2.8,zoom*(e.deltaY<0?1.1:.9)));draw();}},{passive:false});
 function update3D(){if(!viewer||mode!=='3d')return;const wasFPS=viewer.fps,pos=viewer.camera.position.clone(),rotation=viewer.camera.quaternion.clone();viewer.setHouse(window.Engine.buildHouse(D.clone(state)));viewer.house.setStage(6,cut);if(wasFPS){viewer.camera.position.copy(pos);viewer.camera.quaternion.copy(rotation);}}
 function init3D(){if(viewer||!window.Engine)return;try{viewer=window.Engine.createViewer($('three'));const ground=new window.Engine.THREE.Group();window.Engine.box(ground,60,.1,60,0,-.32,0,'#e2e6d8');viewer.scene.add(ground);update3D();$('three').querySelector('.loading').classList.add('done');viewer.paused=mode!=='3d';}catch(e){$('three').querySelector('.loading').textContent='WebGL 3D를 시작할 수 없습니다. 브라우저의 하드웨어 가속 설정을 확인하세요.';}}
 function setMode(next){mode=next;document.querySelectorAll('#mode2d,#mode3d').forEach(b=>{const active=b.id==='mode'+next;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});svg.classList.toggle('hidden',next==='3d');$('three').classList.toggle('visible',next==='3d');$('tools2d').classList.toggle('hidden-ui',next==='3d');$('legend2d').classList.toggle('hidden-ui',next==='3d');$('tools3d').classList.toggle('hidden-ui',next==='2d');if(next==='3d'){init3D();update3D();viewer?.resize();}else{viewer?.setFPS(false);walkUI(false);}if(viewer)viewer.paused=next!=='3d';}
 function walkUI(on){$('walk').classList.toggle('active',on);$('orbit').classList.toggle('active',!on);$('walk-controls').classList.toggle('hidden-ui',!on);$('walk-tip').classList.toggle('hidden-ui',!on);}
 function setFloor(n){floor=n;selected=null;measurement=[];roomChoice='';zoom=1;pan={x:0,z:0};$('floor0').classList.toggle('active',n===0);$('floor1').classList.toggle('active',n===1);$('floor0').setAttribute('aria-pressed',n===0);$('floor1').setAttribute('aria-pressed',n===1);if(viewer?.fps)viewer.floorTo(n);else if(viewer&&mode==='3d')viewer.tweenCamera(n?[12,10,13]:[13,13,17],[0,n?2.5:1.8,0]);draw();properties();}
 $('floor0').onclick=()=>setFloor(0);$('floor1').onclick=()=>setFloor(1);$('mode2d').onclick=()=>setMode('2d');$('mode3d').onclick=()=>setMode('3d');$('orbit').onclick=()=>{viewer?.setFPS(false);walkUI(false);};$('walk').onclick=()=>{if(!viewer)return;cut=false;$('cutaway').classList.remove('active');viewer.house.setStage(6,false);viewer.setFPS(true,floor);walkUI(true);};$('cutaway').onclick=()=>{cut=!cut;$('cutaway').classList.toggle('active',cut);viewer?.house.setStage(6,cut);};
 $('catalog').innerHTML=D.CATALOG.map((item,i)=>`<button data-add="${i}"><span class="symbol" aria-hidden="true"></span>${esc(item[1])}</button>`).join('');
 $('mobile-catalog').innerHTML=$('catalog').innerHTML;document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const [type,label,w,d,h,color]=D.CATALOG[Number(b.dataset.add)];change(()=>{const f={id:'custom-'+crypto.randomUUID(),type,label,w,d,h,color,r:0,floor,x:floor?6.45:2.8,z:floor?5.6:6.3};if(!place(f,false))return;state.furniture.push(f);selected={type:'furniture',id:f.id};});toast(label+' 추가됨');});
 $('select-tool').onclick=()=>{tool='select';$('select-tool').classList.add('active');$('measure-tool').classList.remove('active');draw();};$('measure-tool').onclick=()=>{tool='measure';selected=null;measurement=[];$('select-tool').classList.remove('active');$('measure-tool').classList.add('active');draw();properties();toast('평면도에서 시작점과 끝점을 선택하세요.');};$('zoom-in').onclick=()=>{zoom=Math.min(2.8,zoom*1.2);draw();};$('zoom-out').onclick=()=>{zoom=Math.max(.65,zoom/1.2);draw();};$('fit').onclick=()=>{zoom=1;pan={x:0,z:0};draw();};
 $('mobile-rear-option').onchange=e=>change(()=>{state.rear=e.target.checked;selected=null;});$('mobile-extension-option').onchange=e=>change(()=>{state.extension=e.target.checked;selected=null;});$('rear-option').onchange=e=>change(()=>{state.rear=e.target.checked;selected=null;});$('extension-option').onchange=e=>change(()=>{state.extension=e.target.checked;selected=null;});$('reset').onclick=()=>change(()=>{state=D.clone(D.BASE);selected=null;});$('save').onclick=()=>toast(store()?'현재 설계를 이 브라우저에 저장했습니다.':'저장을 사용할 수 없습니다.');
 $('undo').onclick=()=>{if(!undo.length)return;redo.push(D.clone(state));state=undo.pop();selected=null;store();draw();properties();update3D();$('undo').disabled=!undo.length;$('redo').disabled=false;};$('redo').onclick=()=>{if(!redo.length)return;undo.push(D.clone(state));state=redo.pop();selected=null;store();draw();properties();update3D();$('redo').disabled=!redo.length;$('undo').disabled=false;};
 $('room-select').onchange=e=>{roomChoice=e.target.value;properties();};document.querySelectorAll('[data-material]').forEach(b=>b.onclick=()=>{const r=D.roomGeometry(state,floor).find(r=>r.name===roomChoice);if(r)change(()=>{r.names.forEach(n=>state.floors[n]=b.dataset.material);});});
 $('mobile-more').onclick=()=>$('properties').classList.add('open');$('open-props').onclick=()=>$('properties').classList.add('open');$('close-props').onclick=()=>$('properties').classList.remove('open');$('source-btn').onclick=()=>$('source-dialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
 function download(url,name){const a=document.createElement('a');a.href=url;a.download=name;a.click();}
 $('export').onclick=async()=>{try{if(mode==='3d'){if(!viewer){toast('3D를 불러온 후 내보낼 수 있습니다.');return;}download(viewer.capture(),'청용의집-3D.png');return;}const prevZoom=zoom,prevPan={...pan};zoom=1;pan={x:0,z:0};const oldSel=selected;selected=null;draw();const str=new XMLSerializer().serializeToString(svg);zoom=prevZoom;pan=prevPan;selected=oldSel;draw();const url=URL.createObjectURL(new Blob([str],{type:'image/svg+xml;charset=utf-8'}));const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=2200;c.height=1700;const ctx=c.getContext('2d');ctx.fillStyle='#fafbf6';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(im,0,0,c.width,c.height);download(c.toDataURL('image/png'),`청용의집-${floor?'다락':'1층'}.png`);URL.revokeObjectURL(url);toast('평면도를 PNG로 내보냈습니다.');};im.onerror=()=>{URL.revokeObjectURL(url);toast('이미지 내보내기에 실패했습니다.');};im.src=url;}catch{toast('이미지 내보내기에 실패했습니다.');}};
 addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName)||document.querySelector('dialog[open]'))return;if((e.ctrlKey||e.metaKey)&&e.code==='KeyZ'){e.preventDefault();(e.shiftKey?$('redo'):$('undo')).click();return;}if(mode!=='2d')return;const f=selected?.type==='furniture'&&state.furniture.find(f=>f.id===selected.id);if(f&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyR','Delete','Backspace'].includes(e.code)){e.preventDefault();change(()=>{if(['Delete','Backspace'].includes(e.code)){state.furniture=state.furniture.filter(v=>v.id!==f.id);selected=null;return;}const old={...f};if(e.code==='KeyR')f.r=(f.r+90)%360;else{f.x+=(e.code==='ArrowRight'?.05:e.code==='ArrowLeft'?-.05:0);f.z+=(e.code==='ArrowDown'?.05:e.code==='ArrowUp'?-.05:0);}if(!place(f))Object.assign(f,old);});}if(e.code==='Escape'){selected=null;measurement=[];draw();properties();}});
 document.querySelectorAll('[data-walk]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(viewer)viewer.touchMove=Number(b.dataset.walk);});for(const ev of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>{if(viewer)viewer.touchMove=0;});});
 addEventListener('viewer-ready',()=>{if(mode==='3d')init3D();});addEventListener('walk-floor',e=>{floor=e.detail;$('floor0').classList.toggle('active',floor===0);$('floor1').classList.toggle('active',floor===1);properties();draw();});addEventListener('storage',e=>{if(e.key===D.STORAGE_KEY){state=D.readDesign();selected=null;draw();properties();update3D();toast('다른 페이지의 저장 내용을 반영했습니다.');}});
 draw();properties();window.HouseApp={get state(){return D.clone(state);},get floor(){return floor;},get viewer(){return viewer;},get selected(){return selected;},get measurement(){return D.clone(measurement);},get history(){return undo.length;},setMode,setFloor,draw};
})();
