(()=>{
 const D=window.Design,$=id=>document.getElementById(id),STAGES=[
 ['빈 대지','성토한 패드와 주변 논밭, 도로의 관계를 먼저 살펴봅니다. 건물 정면은 동쪽을 바라보며 기초 공사 영역과 평행하게 놓입니다.','대지 준비 · 지형은 사진 해석','대지'],
 ['기초 형틀 · 철근','사진 1~16의 초기 공정입니다. 형틀과 단열층·배관, 철근을 준비합니다. 이 단계는 과거 사진 상태이며 최신 현장은 다락 골조 단계입니다.','과거 사진 1~16 · 기초 공정','형틀·철근'],
 ['기초 콘크리트 타설','기초 콘크리트가 채워져 1층 프레임을 고정할 패드가 만들어집니다. 다락 바닥의 스팬덱 + 75t RC는 뒤 공정의 계획 사양으로 반영합니다.','기초 타설 완료 · 사진 보강 근거','기초 타설'],
 ['1층 경량철골 조립','1층 기둥과 보를 세워 고정합니다. 최신 사진 17~21에서 1층 골조는 이미 이 공정을 마친 상태입니다. 벽 마감재는 아직 붙이지 않습니다.','1층 골조 완료 · 상부 상승 준비','1층 골조'],
 ['다락 골조 상승','1층 경량철골은 완성·고정된 상태입니다. 그 위로 다락 기둥과 상부 트러스가 올라와 전체 프레임이 완성 높이에 도달한 상태를 보여줍니다.','● 현재 사진 · 2026.10.04 기준','다락 골조'],
 ['지붕 · 외장','사진의 박공 트러스를 따라 금속 지붕과 외장을 덮습니다. 아직 창호·내부 마감과 증축 계획안은 표시하지 않습니다.','향후 공정 · 재료 및 형상 해석','지붕·외장'],
 ['창호 · 마감 · 조경','창호, 내부 칸막이와 가구, 계단·다락 난간을 완성합니다. 선택한 후면 3m 증축안과 다락 3,000 × 3,300mm 계획안, 마당·식재를 함께 보여줍니다.','완공 제안 · 증축안은 계획','마감·조경']
 ];let stage=4,viewer=null,state=D.readDesign(),yardType='pavers',gardenOn=true,garden=null,yard=null,cruising=false,cruiseStart=0,cruiseTimer=null,stageAnimation=0,ready=false;
 function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(window._siteToast);window._siteToast=setTimeout(()=>$('toast').classList.remove('show'),2500);}
 function stopCruise(){cruising=false;clearInterval(cruiseTimer);if(viewer)viewer.cinematic=false;$('cinematic').textContent='▷ 시네마틱 순항';$('cinematic').classList.remove('active');}
 function setStage(n,animate=true,manual=true){n=Math.max(0,Math.min(6,Number(n)));if(manual)stopCruise();const before=stage;stage=n;$('stage-slider').value=n;$('stage-index').textContent=`STAGE ${String(n).padStart(2,'0')} / 06`;$('stage-title').textContent=STAGES[n][0];$('stage-copy').textContent=STAGES[n][1];$('stage-badge').textContent=STAGES[n][2];document.querySelectorAll('[data-stage]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.stage)===n);b.setAttribute('aria-pressed',Number(b.dataset.stage)===n);});$('scene-caption').textContent=n===4?'사진 17~21 기준 · 1층 완료 + 다락 골조 진행':n===6?'동향 완공 제안 · 증축·조경은 계획안':'현장 사진에 기반한 공정 재해석 · 단계 '+n;
  if(!viewer)return;viewer.house.setStage(n);garden.visible=n===6&&gardenOn;yard.visible=n===6;const groups=[...viewer.house.stages,viewer.house.roof];cancelAnimationFrame(stageAnimation);groups.forEach(g=>{g.scale.set(1,1,1);g.position.y=0;});
  if(animate&&before!==n&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const group=n===5?viewer.house.roof:viewer.house.stages[n],start=performance.now();function frame(){const t=Math.min(1,(performance.now()-start)/650),k=t*t*(3-2*t);group.scale.y=n===6?.94+.06*k:.02+.98*k;const anchor=n===4?2.3:n===5?4.1:n===2?-.3:0;group.position.y=anchor*(1-group.scale.y);stageAnimation=t<1?requestAnimationFrame(frame):0;}frame();}
  if(viewer.fps&&n<6){viewer.setFPS(false);walkUI(false);}
 }
 function saveDesign(){try{localStorage.setItem(D.STORAGE_KEY,JSON.stringify(state));}catch{toast('로컬 저장을 사용할 수 없습니다.');}}
 function refreshHouse(){if(!viewer)return;const E=window.Engine;viewer.setHouse(E.buildHouse(D.clone(state)));viewer.house.setStage(stage);$('site-extension').checked=state.extension;$('site-rear').checked=state.rear;}
 function walkUI(on){$('site-walk').classList.toggle('active',on);$('site-orbit').classList.toggle('active',!on);$('site-walk-controls').classList.toggle('hidden-ui',!on);$('site-walk-tip').classList.toggle('hidden-ui',!on);}
 function start(){if(ready||!window.Engine)return;ready=true;const E=window.Engine,{THREE,box,beam,mat,label}=E;
  try{viewer=E.createViewer($('site-three'),{site:true});}catch(e){$('site-three').querySelector('.loading').textContent='WebGL 3D를 시작할 수 없습니다. 하드웨어 가속이 가능한 브라우저로 열어 주세요.';return;}
  const landscape=new THREE.Group();viewer.scene.add(landscape);let randomSeed=721;const rand=()=>{randomSeed=(randomSeed*1664525+1013904223)>>>0;return randomSeed/4294967296;};
  box(landscape,180,.3,180,0,-.22,0,'#bbc39c');
  function pad(){const shape=new THREE.Shape();const p=[[-9,-10],[6,-10],[11,-7],[12,5],[9,11],[-6,10],[-10,3]];p.forEach(([x,z],i)=>i?shape.lineTo(x,-z):shape.moveTo(x,-z));shape.closePath();const geo=new THREE.ExtrudeGeometry(shape,{depth:1.02,bevelEnabled:true,bevelSize:.65,bevelThickness:.03,bevelSegments:1,steps:1});const mesh=new THREE.Mesh(geo,[mat('#c4b18a'),mat('#b5a07b')]);mesh.rotation.x=-Math.PI/2;mesh.position.y=.05;mesh.receiveShadow=true;mesh.castShadow=true;landscape.add(mesh);box(landscape,4,.12,5,5,.55,11.6,'#b6ac8f').rotation.x=-.14;}
  pad();
  function ribbon(g,points,width,color,y){const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(p[0],y,p[1]))),vertices=[],uvs=[],indices=[],steps=100;
   for(let i=0;i<=steps;i++){const t=i/steps,p=curve.getPoint(t),tan=curve.getTangent(t),normal=new THREE.Vector3(-tan.z,0,tan.x).normalize();for(const s of[-1,1]){const v=p.clone().addScaledVector(normal,s*width/2);vertices.push(v.x,v.y,v.z);uvs.push(t,s===-1?0:1);}if(i<steps){const k=i*2;indices.push(k,k+2,k+1,k+1,k+2,k+3);}}
   const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));geo.setIndex(indices);geo.computeVertexNormals();const m=new THREE.Mesh(geo,mat(color,{side:THREE.DoubleSide}));m.receiveShadow=true;g.add(m);return curve;}
  const road=ribbon(landscape,[[-16,-40],[-14,-20],[-13,-3],[-11,9],[-4,14],[10,17],[31,24],[58,31]],3.4,'#929889',.065);ribbon(landscape,[[-16,-40],[-14,-20],[-13,-3],[-11,9],[-4,14],[10,17],[31,24],[58,31]],3.65,'#c9c8b8',.03);
  const creek=ribbon(landscape,[[15,-21],[15,-7],[17,2],[17,9],[14,14],[16,21],[29,26],[40,35]],1.5,'#81a8a2',.01);ribbon(landscape,[[15,-21],[15,-7],[17,2],[17,9],[14,14],[16,21],[29,26],[40,35]],2.1,'#9aab87',-.01);
  for(const [x,z,w,d,col]of[[27,-5,19,17,'#d5cb78'],[46,-6,16,19,'#b7bd77'],[29,16,17,18,'#c7c180'],[47,18,17,20,'#d2c981'],[8,31,20,13,'#b3bc87'],[-7,31,8,12,'#adb583'],[32,-27,26,18,'#b1be81']]){box(landscape,w,.04,d,x,.04,z,col);for(let i=-w/2;i<w/2;i+=.7)box(landscape,.15,.035,d-.5,x+i,.085,z,'#9dac68');for(const xx of[x-w/2,x+w/2])box(landscape,.3,.12,d,xx,.1,z,'#a7b48b');}
  for(const [x,z,w,d]of[[-27,10,12,14],[-28,-9,12,18],[0,-24,18,10]]){box(landscape,w,.055,d,x,.055,z,'#a69c76');for(let i=-w/2;i<w/2;i+=.75)box(landscape,.22,.1,d-.3,x+i,.15,z,'#697d53');}
  function blockWall(points,height=.75,color='#a9afa2',y=.15){for(let i=0;i<points.length-1;i++){const a=new THREE.Vector3(points[i][0],0,points[i][1]),b=new THREE.Vector3(points[i+1][0],0,points[i+1][1]),len=a.distanceTo(b),angle=Math.atan2(b.z-a.z,b.x-a.x);for(let row=0;row<Math.ceil(height/.23);row++)for(let k=0;k<len/.8;k++){const t=(k*.8+(row%2)*.35)/len;if(t>1)continue;const p=a.clone().lerp(b,t);const mesh=box(landscape,.77,.22,.32,p.x,y+row*.23+.11,p.z,color);mesh.rotation.y=-angle;}}}
  blockWall([[-10.8,-9],[-10.8,-2],[-9.2,5],[-5.5,10],[1.5,12]],.8);blockWall([[8,13],[11,9],[13,4]],.7);
  blockWall([[-18,4],[-19,10],[-24,15],[-33,16]],1.15,'#9c9f8d');
  for(let i=0;i<25;i++){const x=-19-i*.56,z=10+i*.25,m=new THREE.Mesh(new THREE.DodecahedronGeometry(.48,0),mat(i%2?'#a3a591':'#8c9988'));m.position.set(x,.72,z);m.scale.set(1.4,.75,.7);m.castShadow=true;landscape.add(m);}
  function tree(g,x,z,height=3,col='#809365',y=.1,type='round'){const r=new THREE.Group();r.position.set(x,y,z);g.add(r);box(r,.13,height*.6,.13,0,height*.3,0,'#7d6b4c');const geo=type==='cone'?new THREE.ConeGeometry(height*.22,height*.78,7):new THREE.IcosahedronGeometry(height*.34,0);const crown=new THREE.Mesh(geo,mat(col));crown.position.y=height*.69;crown.scale.y=type==='cone'?1:1.05;crown.castShadow=true;r.add(crown);if(type!=='cone'){for(let i=0;i<3;i++){const b=new THREE.Mesh(new THREE.IcosahedronGeometry(height*.22,0),mat(i%2?col:'#91a277'));b.position.set((i-1)*height*.19,height*.65+(i%2)*height*.12,(i%2)*height*.18);b.castShadow=true;r.add(b);}}return r;}
  function hills(x,z,sx,sy,sz,col){const mesh=new THREE.Mesh(new THREE.IcosahedronGeometry(1,1),mat(col,{flatShading:true}));mesh.position.set(x,sy*.15,z);mesh.scale.set(sx,sy,sz);mesh.rotation.y=rand()*Math.PI;landscape.add(mesh);}
  const ramp=(v)=>{const t=Math.max(0,Math.min(1,v));return t*t*(3-2*t);};const terrainHeight=(x,z)=>24*Math.exp(-(((x+60)/22)**2)-((z+4)/58)**2)*ramp((-x-30)/20)+25*Math.exp(-(((x+40)/28)**2)-((z+62)/29)**2)*ramp((-z-25)/20)+18*Math.exp(-(((x-24)/27)**2)-((z+83)/28)**2)*ramp((-z-30)/20);
  {const vertices=[],colors=[],color=new THREE.Color(),nx=31,nz=31;const vertex=(i,j)=>{const x=-100+i*5.5,z=-110+j*5.5,h=terrainHeight(x,z);vertices.push(x,h-.22,z);color.set('#819b79');color.offsetHSL(0,-.04,(h/30)*.12+(rand()-.5)*.055);colors.push(color.r,color.g,color.b);};for(let i=0;i<nx;i++)for(let j=0;j<nz;j++){vertex(i,j);vertex(i+1,j);vertex(i,j+1);vertex(i+1,j);vertex(i+1,j+1);vertex(i,j+1);}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.computeVertexNormals();const mountains=new THREE.Mesh(geo,mat('#ffffff',{vertexColors:true,flatShading:true,side:THREE.DoubleSide}));mountains.receiveShadow=true;landscape.add(mountains);}
  for(let i=0;i<95;i++){const west=i<35,x=west?-34-rand()*22:-42+rand()*65,z=west?-30+rand()*55:-31-rand()*25;tree(landscape,x,z,2.4+rand()*4.8,['#6d865f','#7f936b','#94a17b'][i%3],Math.max(.1,terrainHeight(x,z)-.18));}
  for(let i=0;i<10;i++)tree(landscape,18+rand()*28,-25+rand()*22,2.2+rand()*1.5,'#849565');
  function pole(x,z){const g=new THREE.Group();g.position.set(x,.1,z);landscape.add(g);const m=new THREE.Mesh(new THREE.CylinderGeometry(.09,.15,7.8,9),mat('#c1c3b2'));m.position.y=3.9;m.castShadow=true;g.add(m);box(g,.28,1.1,.3,0,.8,0,'#d3bb48');beam(g,[0,6,0],[1.2,6.4,0],.08,'#899c91');box(g,.65,.08,.25,1.2,6.4,0,'#cfd3c4');beam(g,[-.65,7.3,0],[.65,7.3,0],.055,'#859088');return [x,7.4,z];}
  const poles=[pole(-11.6,-8),pole(-10,10),pole(9,19),pole(28,27)];for(let i=0;i<poles.length-1;i++){const a=new THREE.Vector3(...poles[i]),b=new THREE.Vector3(...poles[i+1]),mid=a.clone().lerp(b,.5);mid.y-=.7;const curve=new THREE.QuadraticBezierCurve3(a,mid,b);const geo=new THREE.BufferGeometry().setFromPoints(curve.getPoints(24));landscape.add(new THREE.Line(geo,new THREE.LineBasicMaterial({color:'#586e65'})));}
  function village(x,z,w,d,c){const g=new THREE.Group();g.position.set(x,.1,z);landscape.add(g);box(g,w,2.6,d,0,1.3,0,'#e0ded0');for(const sign of[-1,1]){const r=box(g,w+.5,.12,d*.58,0,2.9,sign*d*.23,c);r.rotation.x=sign*.33;}box(g,1.1,1,.03,-w*.2,1.4,d/2+.025,'#5c7571');box(g,.8,2,.03,w*.24,1,d/2+.025,'#9e997f');}
  village(-24,9,6,5,'#697d77');village(-27,20,5.5,4,'#a0805e');village(-31,-4,7,5,'#7499a0');village(-22,-20,6,4,'#577b77');
  garden=new THREE.Group();viewer.scene.add(garden);yard=new THREE.Group();viewer.scene.add(yard);
  function plant(g,x,z,h,col,name,type='round'){tree(g,x,z,h,col,1.13,type);if(name)label(g,name,x,h+1.5,z,'#516c4c',.36);}
  // Front is east (+X); front-left is south (+Z), independent of reference image north.
  const monument=new THREE.Group();monument.position.set(3.4,1.13,7.15);garden.add(monument);box(monument,1.55,.14,1.3,0,.07,0,'#adae9f');box(monument,1.1,.18,.75,0,.24,0,'#919787');const stone=box(monument,.63,1.45,.2,0,1.04,0,'#66786a');stone.rotation.y=Math.PI/2;label(garden,'비석',3.4,3.05,7.15,'#53634e',.35);
  const inscription=document.createElement('canvas');inscription.width=128;inscription.height=256;const ictx=inscription.getContext('2d');ictx.fillStyle='#758475';ictx.fillRect(0,0,128,256);ictx.fillStyle='#e6e5d7';ictx.font='28px serif';ictx.textAlign='center';['기','념','비'].forEach((c,i)=>ictx.fillText(c,64,65+i*55));const tm=new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(inscription)});const plaque=new THREE.Mesh(new THREE.PlaneGeometry(.43,1.15),tm);plaque.position.set(.106,1.04,0);plaque.rotation.y=Math.PI/2;monument.add(plaque);
  plant(garden,3.4,5.75,1.8,'#4b755c','주목','cone');plant(garden,3.4,8.5,1.8,'#4b755c',null,'cone');
  plant(garden,-6.7,-7.9,2.8,'#c4b77e','산수유');plant(garden,-7.3,5.1,2.2,'#b2a2b7','라일락');plant(garden,8.9,-5.8,3.2,'#78945d','비파');plant(garden,10,3.3,2.6,'#99a166','무화과');plant(garden,8.1,8.0,2.9,'#b6ab92','체리');
  function fence(points){for(let i=0;i<points.length-1;i++){const [x,z]=points[i],[xx,zz]=points[i+1],len=Math.hypot(xx-x,zz-z),angle=-Math.atan2(zz-z,xx-x);const b=box(garden,len,.6,.2,(x+xx)/2,1.43,(z+zz)/2,'#b09c7f');b.rotation.y=angle;for(let k=0;k<len;k+=.18){const t=k/len;box(garden,.035,.6,.035,x+(xx-x)*t,2.03,z+(zz-z)*t,'#667764');}for(const y of[1.75,2.3])beam(garden,[x,y,z],[xx,y,zz],.04,'#697963');}}
  fence([[-7.5,9],[.3,10.1]]);fence([[7.5,10.7],[10.5,6],[11,-5]]);fence([[-8,-8],[-5.5,-9]]);
  for(let x=-4.7;x<7.8;x+=.62){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.45,0),mat('#768b57'));m.position.set(x,1.5,-9.2);m.scale.set(1,.8,.8);m.castShadow=true;garden.add(m);}label(garden,'북측 · 녹차 생울타리',1.2,2.6,-9.2,'#526a4a',.52);
  function makeYard(){E.disposeTree(yard);yard=new THREE.Group();viewer.scene.add(yard);box(yard,17,.035,18,1,1.13,0,yardType==='concrete'?'#c0c2b7':'#a9b58a');
   if(yardType==='pavers'){for(let x=-7;x<9.5;x+=.84)for(let z=-8.6;z<8.5;z+=.84){if(x>-2.3&&x<2.6&&z>-4.3&&z<4.3)continue;box(yard,.72,.018,.72,x,1.157,z,(Math.round(x+z)*7)%3===0?'#c9c8b4':'#d5d3c2');}}
   for(let x=3.1;x<=7.5;x+=.82)box(yard,.8,.025,1.2,x,1.165,1.65,'#d8d5c1');for(let z=3;z<9.7;z+=.8)box(yard,1.2,.025,.77,7.55,1.165,z,'#d8d5c1');for(let z=2.2;z<7;z+=.7)box(yard,1.2,.025,.65,3.5,1.165,z,'#d0cdb8');
   box(yard,8.5,.018,4.8,-.1,1.15,0,'#b5b49b'); // concealed below body / gravel drainage strip
   box(yard,3.5,.025,4.7,7.7,1.17,6.6,'#d1cfbc');yard.visible=stage===6;E.batchStatic(yard);
  }
  E.batchStatic(landscape);E.batchStatic(garden);window._makeCheongyongYard=makeYard;makeYard();refreshHouse();setStage(stage,false,false);viewer.setTime($('time-slider').value);$('site-three').querySelector('.loading').classList.add('done');
  viewer.renderer.domElement.addEventListener('pointerdown',()=>{if(cruising)stopCruise();});window.SiteApp={get viewer(){return viewer;},get stage(){return stage;},get state(){return D.clone(state);},get cruising(){return cruising;},get garden(){return garden;},get yard(){return yard;},setStage};
 }
 $('stage-buttons').innerHTML=STAGES.map((s,i)=>`<button data-stage="${i}" class="${i===4?'active current':''}" aria-pressed="${i===4}"><span class="number">${String(i).padStart(2,'0')}</span><span>${s[3]}</span></button>`).join('');document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>setStage(b.dataset.stage));$('stage-slider').oninput=e=>setStage(e.target.value);$('current-stage').onclick=()=>setStage(4);
 $('cinematic').onclick=()=>{if(!viewer)return;if(cruising){stopCruise();return;}viewer.setFPS(false);walkUI(false);viewer.cinematic=true;cruising=true;cruiseStart=performance.now();setStage(0,true,false);$('cinematic').textContent='Ⅱ 순항 멈추기';$('cinematic').classList.add('active');cruiseTimer=setInterval(()=>{const elapsed=performance.now()-cruiseStart,n=Math.floor(elapsed/5500);if(n>6){stopCruise();return;}if(n!==stage)setStage(n,true,false);},400);};
 $('time-slider').oninput=e=>{const val=Number(e.target.value);$('time-label').textContent=String(Math.floor(val)).padStart(2,'0')+':'+String(Math.round((val%1)*60)).padStart(2,'0');viewer?.setTime(val);};
 document.querySelectorAll('[data-yard]').forEach(b=>b.onclick=()=>{yardType=b.dataset.yard;document.querySelectorAll('[data-yard]').forEach(a=>a.classList.toggle('active',a===b));window._makeCheongyongYard?.();if(stage!==6)toast('마당 처리안은 6단계 완공에서 보입니다.');});$('garden-toggle').onchange=e=>{gardenOn=e.target.checked;if(garden)garden.visible=stage===6&&gardenOn;};
 $('site-extension').onchange=e=>{state.extension=e.target.checked;saveDesign();refreshHouse();};$('site-rear').onchange=e=>{state.rear=e.target.checked;saveDesign();refreshHouse();};
 $('site-orbit').onclick=()=>{stopCruise();viewer?.setFPS(false);walkUI(false);};$('site-walk').onclick=()=>{if(!viewer)return;stopCruise();setStage(6);viewer.setFPS(true,0);walkUI(true);};$('walk-floor0').onclick=()=>viewer?.floorTo(0);$('walk-floor1').onclick=()=>viewer?.floorTo(1);
 $('site-settings').onclick=()=>document.querySelector('.site-controls').classList.toggle('open');$('site-settings-close').onclick=()=>document.querySelector('.site-controls').classList.remove('open');$('evidence-btn').onclick=()=>$('evidence-dialog').showModal();$('garden-btn').onclick=()=>$('garden-dialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('site-capture').onclick=()=>{if(!viewer){toast('3D 장면을 준비한 후 저장할 수 있습니다.');return;}const a=document.createElement('a');a.href=viewer.capture();a.download=`청용리-공정${stage}.png`;a.click();toast('현재 장면을 PNG로 저장했습니다.');};
 document.querySelectorAll('[data-site-walk]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(viewer)viewer.touchMove=Number(b.dataset.siteWalk);});for(const ev of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>{if(viewer)viewer.touchMove=0;});});
 addEventListener('storage',e=>{if(e.key===D.STORAGE_KEY){state=D.readDesign();refreshHouse();toast('공간 설계의 저장 내용을 반영했습니다.');}});addEventListener('viewer-ready',start);if(window.Engine)start();
})();
