const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
const browser=await chromium.launch({...(process.env.BROWSER_PATH ? {executablePath:process.env.BROWSER_PATH} : {}),headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});let errors=[],checks=[];const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const path=require('node:path'),crypto=require('node:crypto'),root=path.resolve(__dirname,'..');const origin=process.env.BASE_URL || 'http://localhost:8765/codex-work/';const out=path.join(root,'evidence/');fs.mkdirSync(out,{recursive:true});const hashes=Object.fromEntries(['house-plan.html','site-sim.html'].map(name=>[name,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,name))).digest('hex')]));
function check(name,value){assert(value,name);checks.push(name);console.log('PASS '+name)}
async function xy(x,z){return page.evaluate(({x,z})=>{let svg=document.querySelector('#plan'),p=svg.createSVGPoint();p.x=x;p.y=z;p=p.matrixTransform(svg.getScreenCTM());return {x:p.x,y:p.y}}, {x,z})}
await page.goto(origin+'house-plan.html');await page.waitForFunction(()=>!!window.houseApp);await page.screenshot({path:out+'plan-desktop.png'});
check('본채 8,000mm 및 후면 3,000mm 도면 표시',await page.locator('#plan').textContent().then(t=>t.includes('8,000')&&t.includes('3,000')&&t.includes('후문')));
const area=+(await page.locator('#area').textContent());check('면적은 후면 증축 포함 자동 계산',area>50&&area<60);
let a=await xy(1500,3200),b=await xy(1140,3200);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:8});await page.mouse.up();let sofa=await page.evaluate(()=>houseApp.state.furniture.find(f=>f.id==='sofa'));
check('가구 드래그 및 외벽 스냅',sofa.x===1150);await page.getByRole('button',{name:'실행 취소',exact:true}).click();check('드래그 실행 취소',(await page.evaluate(()=>houseApp.state.furniture.find(f=>f.id==='sofa').x))===1500);await page.getByRole('button',{name:'↷ 다시',exact:true}).click();check('다시 실행',(await page.evaluate(()=>houseApp.state.furniture.find(f=>f.id==='sofa').x))===1150);
a=await xy(1800,2200);await page.mouse.click(a.x,a.y);await page.locator('#fw').fill('1300');await page.locator('#fw').dispatchEvent('change');await page.getByRole('button',{name:'90° 회전',exact:true}).click();check('가구 크기 및 회전',(await page.evaluate(()=>{let f=houseApp.state.furniture.find(f=>f.id==='table');return f.w===1300&&f.r===90})));await page.locator('#room').selectOption('living');await page.locator('#material').selectOption('tile');check('바닥재 변경',(await page.evaluate(()=>houseApp.state.floors.living))==='tile');
await page.getByRole('button',{name:'측정',exact:true}).click();a=await xy(0,4500);b=await xy(8000,4500);await page.mouse.click(a.x,a.y);await page.mouse.click(b.x,b.y);check('두 점 거리 측정',(await page.locator('#plan').textContent()).includes('8,000 mm'));
await page.getByRole('button',{name:'벽 변경',exact:true}).click();a=await xy(4900,2200);await page.mouse.click(a.x,a.y);await page.locator('#wallpos').fill('5100');await page.locator('#wallpos').dispatchEvent('change');check('일반 벽 위치 변경',(await page.evaluate(()=>houseApp.state.walls[0].x1))===5100);await page.getByRole('button',{name:'철거',exact:true}).click();check('일반 벽 철거 및 면적 재계산',(await page.evaluate(()=>!houseApp.state.walls[0].active))&& +(await page.locator('#area').textContent())!==area);
await page.getByRole('button',{name:'실행 취소',exact:true}).click();await page.getByRole('button',{name:'실행 취소',exact:true}).click();await page.getByRole('button',{name:'벽 변경',exact:true}).click();a=await xy(2900,-2200);await page.mouse.click(a.x,a.y);await page.getByRole('button',{name:'철거',exact:true}).click();check('후면 일반 벽 철거와 면적 갱신',await page.evaluate(()=>!houseApp.state.walls.find(w=>w.id==='rearleft').active&&houseApp.rooms.find(r=>r.id==='storage').area===0));await page.getByRole('button',{name:'실행 취소',exact:true}).click();
await page.locator('#floor').selectOption('attic');check('다락·보이드·증축 층 전환',(await page.locator('#plan').textContent()).includes('VOID'));await page.locator('#catalog').selectOption('chair');await page.getByRole('button',{name:'+ 현재 층에 배치',exact:true}).click();let newId=await page.evaluate(()=>houseApp.state.furniture.at(-1).id);check('현재 층 가구 추가',(await page.evaluate(()=>houseApp.state.furniture.at(-1).floor))==='attic');await page.getByRole('button',{name:'설계안 저장',exact:true}).click();check('로컬 저장',(await page.evaluate(()=>!!localStorage.getItem('cheongyong-house-v1'))));
let dl=page.waitForEvent('download');await page.getByRole('button',{name:'평면 PNG ↓',exact:true}).click();let d=await dl;await d.saveAs(out+'plan-export.png');check('평면 PNG 내보내기',fs.statSync(out+'plan-export.png').size>10000);
await page.getByRole('button',{name:'3D 공간',exact:true}).click();await page.waitForFunction(()=>houseApp.threeReady&&document.querySelector('#three canvas'),{timeout:30000});await page.waitForTimeout(1500);check('3D 다락 가구 높이 동기화',await page.evaluate(id=>houseApp.scene.getObjectByName(id).position.y>2.5,newId));check('회전·재질 3D 동기화',await page.evaluate(()=>Math.abs(houseApp.scene.getObjectByName('table').rotation.y+Math.PI/2)<.001));
await page.screenshot({path:out+'house-complete.png'});await page.getByRole('button',{name:'지붕 열기',exact:true}).click();await page.waitForTimeout(500);await page.screenshot({path:out+'house-interior.png'});check('상부 보이드 안전 경계',await page.evaluate(()=>!houseApp.canMove(3,2)&&houseApp.canMove(5.4,2)));
await page.getByRole('button',{name:'1인칭 둘러보기',exact:true}).click();await page.waitForTimeout(300);check('다락 1인칭 높이',await page.evaluate(()=>houseApp.walk&&houseApp.camera.position.y>4));await page.getByRole('button',{name:'1인칭 둘러보기',exact:true}).click();await page.locator('#floor').selectOption('f1');await page.getByRole('button',{name:'1인칭 둘러보기',exact:true}).click();await page.evaluate(()=>houseApp.camera.position.set(4.45,1.68,3));await page.keyboard.down('w');await page.waitForFunction(()=>houseApp.floor==='attic'&&houseApp.camera.position.y>3.9,{timeout:25000});await page.keyboard.up('w');check('계단 이동으로 1층에서 다락에 도달',await page.evaluate(()=>houseApp.floor==='attic'&&houseApp.camera.position.y>3.9));await page.getByRole('button',{name:'1인칭 둘러보기',exact:true}).click();
dl=page.waitForEvent('download');await page.getByRole('button',{name:'3D PNG ↓',exact:true}).click();d=await dl;await d.saveAs(out+'house-export.png');check('3D PNG 내보내기',fs.statSync(out+'house-export.png').size>10000);
await page.getByRole('button',{name:'2D 평면',exact:true}).click();const site=await context.newPage();site.on('pageerror',e=>errors.push(e.message));site.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await site.goto(origin+'site-sim.html');await site.waitForFunction(()=>window.siteApp?.threeReady&&document.querySelector('#three canvas'),{timeout:30000});check('두 페이지 저장 설계안 공유',(await site.evaluate(()=>siteApp.state.furniture.at(-1).id))===newId);await site.waitForTimeout(1000);await site.screenshot({path:out+'site-foundation.png'});
for(let i=0;i<7;i++){await site.locator(`[data-stage="${i}"]`).click();await site.waitForTimeout(700);check('공사 단계 '+i+' 전환',await site.evaluate(n=>siteApp.stage===n,[i][0]));}
await site.locator('#labels').click();check('조경 이름 표시 토글',await site.evaluate(()=>{let seen=false;siteApp.scene.userData.garden.traverse(o=>{if(o.userData.label&&o.visible)seen=true});return seen}));await site.locator('#labels').click();await site.screenshot({path:out+'site-complete.png'});await site.locator('#time').fill('18');await site.locator('#time').dispatchEvent('input');check('시간대 변경',(await site.locator('#timeLabel').textContent())==='18:00');await site.screenshot({path:out+'site-sunset.png'});
await site.locator('#visitFloor').selectOption('attic');await site.locator('#walk').click();await site.waitForTimeout(300);check('현장 다락 높이 오프셋',await site.evaluate(()=>siteApp.camera.position.y>4.5));await site.locator('#walk').click();await site.locator('#cinema').click();await site.waitForFunction(()=>siteApp.stage!==6,{timeout:15000});check('시네마틱 자동 단계 진행',(await site.evaluate(()=>siteApp.stage))!==6);await site.locator('#cinema').click();
// Separate live tab sees the saved edit through the storage event.
await page.locator('#floor').selectOption('f1');await page.locator('#catalog').selectOption('chair');await page.getByRole('button',{name:'+ 현재 층에 배치',exact:true}).click();await page.getByRole('button',{name:'설계안 저장',exact:true}).click();await site.waitForTimeout(250);check('저장 이벤트로 열린 현장 탭 실시간 갱신',(await page.evaluate(()=>houseApp.state.furniture.length))===(await site.evaluate(()=>siteApp.state.furniture.length)));
await page.close();await site.close();const mobileContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,storageState:await context.storageState()});const mobile=await mobileContext.newPage();mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(origin+'house-plan.html');await mobile.waitForFunction(()=>window.houseApp);check('모바일 가로 넘침 없음',await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.screenshot({path:out+'plan-mobile.png',fullPage:true});await mobile.getByRole('button',{name:'3D 공간',exact:true}).tap();await mobile.waitForFunction(()=>houseApp.threeReady);await mobile.locator('#walk').tap();check('모바일 이동 버튼 표시',await mobile.locator('#walkpad').isVisible());await mobile.locator('#walk').click();await mobile.goto(origin+'site-sim.html');await mobile.waitForFunction(()=>window.siteApp?.threeReady);await mobile.locator('[data-stage="6"]').click();await mobile.waitForTimeout(800);await mobile.screenshot({path:out+'site-mobile.png',fullPage:true});check('현장 모바일 가로 넘침 없음',await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await mobile.getByRole('link',{name:'인테리어 설계 ↗',exact:true}).click();check('페이지 간 왕복 링크',mobile.url().endsWith('house-plan.html'));
check('자바스크립트 및 리소스 오류 없음',errors.length===0);fs.writeFileSync(out+'verification.json',JSON.stringify({date:new Date().toISOString(),browser:'Chromium 1200 / SwiftShader',sourceSHA256:hashes,checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,errors,checks},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
