const {chromium}=require('/tmp/cheongyong-viewer-qa/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const results=[],errors=[];
const record=(name,data)=>{results.push({name,passed:true,...data});console.log('PASS',name)};
const url='http://127.0.0.1:8768/codex-work/';
async function svgPoint(page,x,z){return page.evaluate(({x,z})=>{const svg=document.getElementById('plan-svg'),p=svg.createSVGPoint();p.x=x*1000;p.y=z*1000;const q=p.matrixTransform(svg.getScreenCTM());return {x:q.x,y:q.y};},{x,z});}
async function dragPoint(page,a,b){await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:10});await page.mouse.up();}
async function watch(page){page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text());});}
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1440,height:1000},ignoreHTTPSErrors:true});
 const page=await context.newPage();await watch(page);await page.goto(url+'house-plan.html');await page.waitForFunction(()=>window.HouseApp&&window.Engine);
 const start=await page.evaluate(()=>HouseApp.state);assert.equal(start.rear,true);assert.equal(start.extension,true);assert.equal(await page.locator('[data-wall="front"]').count(),2);
 record('수정 폭 8m · 후문 · 두 층 초기 도면',{area:await page.evaluate(()=>Design.roomGeometry(HouseApp.state,0).reduce((a,r)=>a+r.area,0))});
 await page.locator('[data-furniture="coffee"]').click();await page.locator('#prop-w').fill('1200');await page.locator('#prop-w').press('Tab');assert.equal(await page.evaluate(()=>HouseApp.state.furniture.find(f=>f.id==='coffee').w),1.2);
 await page.click('#rotate-item');assert.equal(await page.evaluate(()=>HouseApp.state.furniture.find(f=>f.id==='coffee').r),90);
 await page.click('#undo');assert.equal(await page.evaluate(()=>HouseApp.state.furniture.find(f=>f.id==='coffee').r),0);await page.click('#redo');assert.equal(await page.evaluate(()=>HouseApp.state.furniture.find(f=>f.id==='coffee').r),90);
 record('가구 실제 치수 변경 · 90도 회전 · 취소/다시 실행');
 const before=await page.evaluate(()=>HouseApp.state.furniture.find(f=>f.id==='coffee'));await dragPoint(page,await svgPoint(page,before.x,before.z),await svgPoint(page,.41,5.65));const after=await page.evaluate(()=>HouseApp.state.furniture.find(f=>f.id==='coffee'));assert.ok(Math.abs(after.x-(.1+DesignBounds(after).w/2))<.005);assert.notEqual(after.z,before.z);record('가구 드래그 · 벽 자동 맞춤',{position:[after.x,after.z]});
 // Real pointer interaction with resize/rotate handles.
 await page.locator('[data-furniture="coffee"]').click();let hb=await page.locator('[data-handle="resize"]').boundingBox();await dragPoint(page,{x:hb.x+hb.width/2,y:hb.y+hb.height/2},{x:hb.x+hb.width/2+8,y:hb.y+hb.height/2+10});const resized=await page.evaluate(()=>HouseApp.state.furniture.find(f=>f.id==='coffee'));assert.ok(resized.w!==after.w||resized.d!==after.d);record('가구 크기 손잡이 드래그');
 await page.click('#measure-tool');await page.mouse.click(...Object.values(await svgPoint(page,1,4)));await page.mouse.click(...Object.values(await svgPoint(page,4,4)));const m=await page.evaluate(()=>HouseApp.measurement);assert.equal(m.length,2);assert.ok(Math.abs(Math.hypot(m[1].x-m[0].x,m[1].z-m[0].z)-3)<.01);record('두 점 측정 · 3,000mm');
 await page.click('#select-tool');await page.mouse.click(...Object.values(await svgPoint(page,2.8,1.3)));await page.waitForSelector('#demolish');const roomCount=await page.evaluate(()=>Design.roomGeometry(HouseApp.state,0).length);await page.click('#demolish');assert.equal(await page.evaluate(()=>Design.roomGeometry(HouseApp.state,0).length),roomCount-1);const joined=await page.evaluate(()=>Design.roomGeometry(HouseApp.state,0).find(r=>r.names.includes('세탁·다용도실')));assert.ok(joined.names.includes('후면 홀'));record('비내력 칸막이 철거 · 방 병합 · 면적 재계산',{mergedArea:joined.area});
 await page.click('#undo');await page.mouse.click(...Object.values(await svgPoint(page,2.8,1.3)));await page.locator('#wall-position').fill('2900');await page.locator('#wall-position').press('Tab');assert.equal(await page.evaluate(()=>HouseApp.state.walls.find(w=>w.id==='rear-laundry').x1),2.9);record('칸막이 위치 변경');await page.click('#undo');
 await page.mouse.click(...Object.values(await svgPoint(page,.05,5)));assert.equal(await page.locator('#demolish').count(),0);assert.match(await page.locator('#property-content').innerText(),/편집 잠금/);record('외곽 구조 보호');
 await page.selectOption('#room-select','거실·주방');await page.click('[data-material="stone"]');assert.equal(await page.evaluate(()=>HouseApp.state.floors['거실·주방']),'stone');await page.click('#save');const saved=await page.evaluate(()=>HouseApp.state);await page.reload();await page.waitForFunction(()=>window.HouseApp);assert.deepEqual(await page.evaluate(()=>HouseApp.state),saved);record('바닥재 변경 · 로컬 저장 · 재로드 복원');
 const download=page.waitForEvent('download');await page.click('#export');const dl=await download;await dl.saveAs(__dirname+'/verified-plan-export.png');assert.equal((await dl.failure()),null);assert.ok(fs.statSync(__dirname+'/verified-plan-export.png').size>10000);record('2D PNG 내보내기');
 await page.click('#floor1');await page.click('#mode3d');await page.waitForFunction(()=>HouseApp.viewer?.house);await page.evaluate(()=>HouseApp.viewer.paused=true);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>HouseApp.viewer.house.roof.visible),true);assert.equal(await page.evaluate(()=>Design.insideFloor(HouseApp.state,1,2,5)),false);assert.equal(await page.evaluate(()=>Design.insideFloor(HouseApp.state,1,6,5)),true);const loftY=await page.evaluate(()=>{let y;HouseApp.viewer.house.root.traverse(o=>{if(o.userData.furnitureId==='loftbed')y=o.position.y;});return y;});assert.equal(loftY,2.3);record('완성형 3D · 다락 보이드 · 가구 층 높이');
 await page.click('#cutaway');await page.evaluate(()=>{const v=HouseApp.viewer;v.renderer.render(v.scene,v.camera);});assert.equal(await page.evaluate(()=>HouseApp.viewer.house.roof.visible),false);await page.screenshot({path:__dirname+'/house-cutaway-desktop.png'});await page.click('#walk');assert.equal(await page.evaluate(()=>HouseApp.viewer.fps),true);assert.ok(Math.abs(await page.evaluate(()=>HouseApp.viewer.camera.position.y)-3.7)<.01);
 await page.evaluate(()=>{const v=HouseApp.viewer;v.camera.position.copy(v.worldPos(5.13,3.7,4.05));v.camera.rotation.set(0,0,0);});await page.evaluate(()=>HouseApp.viewer.paused=false);await page.keyboard.down('KeyA');await page.waitForTimeout(800);await page.keyboard.up('KeyA');await page.evaluate(()=>HouseApp.viewer.paused=true);const voidX=await page.evaluate(()=>HouseApp.viewer.camera.position.x+4);assert.ok(voidX>=5.1);record('다락 1인칭 높이 · 보이드 추락 방지',{localX:voidX});
 await page.click('#floor0');assert.equal(await page.evaluate(()=>HouseApp.viewer.camera.position.y),1.6);
 await page.evaluate(()=>{const v=HouseApp.viewer;v.floorTo(0);v.camera.position.copy(v.worldPos(4.35,1.6,7.12));});await page.evaluate(()=>HouseApp.viewer.paused=false);await page.keyboard.down('KeyW');await page.waitForFunction(()=>HouseApp.viewer.floor===1,null,{timeout:20000});await page.keyboard.up('KeyW');await page.evaluate(()=>HouseApp.viewer.paused=true);assert.equal(await page.evaluate(()=>HouseApp.viewer.floor),1);assert.ok(Math.abs(await page.evaluate(()=>HouseApp.viewer.camera.position.y)-3.7)<.01);record('1층에서 계단을 실제 이동해 다락까지 연속 상승');await page.click('#orbit');await page.evaluate(()=>{const v=HouseApp.viewer;v.renderer.render(v.scene,v.camera);});await page.screenshot({path:__dirname+'/house-3d-desktop.png'});
 await page.click('#mode2d');const site=await context.newPage();await watch(site);await site.goto(url+'site-sim.html');await site.waitForFunction(()=>window.SiteApp?.viewer?.house);await site.evaluate(()=>SiteApp.viewer.paused=true);assert.equal(await site.evaluate(()=>SiteApp.stage),4);assert.equal(await site.evaluate(()=>SiteApp.viewer.house.root.rotation.y),Math.PI/2);assert.deepEqual(await site.evaluate(()=>SiteApp.state),saved);record('현장 초기 단계 4 · 정면 동향 · 두 페이지 저장 데이터 공유');
 const visibility=[];for(let n=0;n<7;n++){await site.click(`[data-stage="${n}"]`);await site.waitForFunction(n=>Math.abs(SiteApp.viewer.house.stages[n].scale.y-1)<.001,n);await site.waitForTimeout(100);const a=await site.evaluate(()=>({stage:SiteApp.stage,visible:SiteApp.viewer.house.stages.map(g=>g.visible),roof:SiteApp.viewer.house.roof.visible,additions:SiteApp.viewer.house.roof.getObjectByName('planned-addition-roofs').visible,garden:SiteApp.garden.visible}));assert.equal(a.stage,n);assert.equal(a.roof,n>=5);assert.equal(a.additions,n===6);assert.equal(a.garden,n===6);visibility.push(a);}record('7단계 전환 · 현재 상부 골조 · 계획 증축 분리',{visibility});
 await site.evaluate(()=>{const v=SiteApp.viewer;v.renderer.render(v.scene,v.camera);});await site.screenshot({path:__dirname+'/site-completed-desktop.png'});await site.click('#current-stage');await site.waitForFunction(()=>SiteApp.viewer.house.stages[4].scale.y===1);await site.evaluate(()=>{const v=SiteApp.viewer;v.renderer.render(v.scene,v.camera);});await site.screenshot({path:__dirname+'/site-current-desktop.png'});
 const beforeSun=await site.evaluate(()=>SiteApp.viewer.sun.position.toArray());await site.locator('#time-slider').evaluate(e=>{e.value='18';e.dispatchEvent(new Event('input',{bubbles:true}));});const afterSun=await site.evaluate(()=>SiteApp.viewer.sun.position.toArray());assert.notDeepEqual(beforeSun,afterSun);assert.equal(await site.locator('#time-label').innerText(),'18:00');record('시간대 슬라이더 · 태양과 그림자 변경');
 await site.click('#cinematic');await site.evaluate(()=>SiteApp.viewer.paused=false);await site.waitForTimeout(250);await site.evaluate(()=>SiteApp.viewer.paused=true);assert.equal(await site.evaluate(()=>SiteApp.cruising),true);await site.waitForTimeout(5800);assert.equal(await site.evaluate(()=>SiteApp.stage),1);await site.click('#cinematic');assert.equal(await site.evaluate(()=>SiteApp.cruising),false);record('시네마틱 카메라 · 공정 자동 진행 · 중지');
 await site.click('#site-walk');assert.equal(await site.evaluate(()=>SiteApp.stage),6);await site.click('#walk-floor1');assert.ok(Math.abs(await site.evaluate(()=>SiteApp.viewer.camera.position.y)-5.05)<.01);await site.click('#site-orbit');record('현장 1인칭 · 다락 높이 오프셋');
 await site.uncheck('#site-extension');await page.waitForFunction(()=>HouseApp.state.extension===false);assert.equal(await page.locator('#extension-option').isChecked(),false);await site.check('#site-extension');await page.waitForFunction(()=>HouseApp.state.extension===true);record('다른 탭 편집 내용 실시간 반영');
 await site.click('[data-yard="grass"]');assert.equal(await site.locator('[data-yard="grass"]').getAttribute('class'),'active');await site.click('[data-yard="pavers"]');await site.uncheck('#garden-toggle');assert.equal(await site.evaluate(()=>SiteApp.garden.visible),false);await site.check('#garden-toggle');record('마당 재료 · 조경 표시 제어');
 const dl3=site.waitForEvent('download');await site.click('#site-capture');await(await dl3).saveAs(__dirname+'/verified-site-export.png');assert.ok(fs.statSync(__dirname+'/verified-site-export.png').size>20000);record('3D PNG 내보내기');
 const renderInfo=await site.evaluate(()=>SiteApp.viewer.renderer.info.render);record('대지 렌더링 성능',{renderInfo});assert.ok(renderInfo.calls<700);
 await context.close();
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1,ignoreHTTPSErrors:true});const mp=await mobile.newPage();await watch(mp);await mp.goto(url+'house-plan.html');await mp.waitForFunction(()=>window.HouseApp&&window.Engine);assert.equal(await mp.evaluate(()=>document.documentElement.scrollWidth),390);await mp.screenshot({path:__dirname+'/house-mobile.png',fullPage:true});await mp.click('#open-props');assert.equal(await mp.locator('#properties').evaluate(e=>e.classList.contains('open')),true);await mp.click('#close-props');await mp.click('#floor1');await mp.click('#mode3d');await mp.waitForFunction(()=>HouseApp.viewer?.house);await mp.evaluate(()=>{const v=HouseApp.viewer;v.paused=true;v.renderer.render(v.scene,v.camera);});await mp.screenshot({path:__dirname+'/house-3d-mobile.png',fullPage:true});record('390px 모바일 · 층 전환 · 속성 패널 · 3D');
 await mp.goto(url+'site-sim.html');await mp.waitForFunction(()=>window.SiteApp?.viewer?.house);await mp.evaluate(()=>{const v=SiteApp.viewer;v.paused=true;v.renderer.render(v.scene,v.camera);});assert.equal(await mp.evaluate(()=>document.documentElement.scrollWidth),390);await mp.waitForTimeout(100);await mp.screenshot({path:__dirname+'/site-mobile.png'});await mp.click('[data-stage="6"]');await mp.waitForFunction(()=>SiteApp.viewer.house.stages[6].scale.y===1);await mp.evaluate(()=>{const v=SiteApp.viewer;v.renderer.render(v.scene,v.camera);});await mp.screenshot({path:__dirname+'/site-completed-mobile.png'});await mp.click('#site-settings');assert.equal(await mp.locator('.site-controls').isVisible(),true);await mp.click('#site-settings-close');assert.equal(await mp.locator('.site-controls').isVisible(),false);record('모바일 빛과 조경 설정 열기/닫기');
 const cdp=await mobile.newCDPSession(mp);const bounds=await mp.locator('#site-three canvas').boundingBox();const a={x:Math.round(bounds.width*.46),y:Math.round(bounds.y+bounds.height*.5)};await mp.evaluate(()=>SiteApp.viewer.paused=false);const beforeCam=await mp.evaluate(()=>SiteApp.viewer.camera.position.toArray());await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...a,id:1,radiusX:2,radiusY:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:a.x+45,y:a.y+12,id:1,radiusX:2,radiusY:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await mp.waitForTimeout(500);await mp.evaluate(()=>SiteApp.viewer.paused=true);assert.notDeepEqual(await mp.evaluate(()=>SiteApp.viewer.camera.position.toArray()),beforeCam);record('모바일 실제 터치 궤도 회전');await mobile.close();
 const offline=await browser.newContext({viewport:{width:1000,height:800}});await offline.route('**/cdn.jsdelivr.net/**',r=>r.abort());const offpage=await offline.newPage();await offpage.goto(url+'house-plan.html');await offpage.waitForFunction(()=>window.HouseApp);await offpage.click('#mode3d');await offpage.waitForSelector('.loading.error');await offpage.click('#mode2d');assert.equal(await offpage.locator('#plan-svg.hidden').count(),0);record('CDN 차단 시 3D 오류 안내 · 2D 계속 동작');await offline.close();
 assert.deepEqual(errors,[]);record('정상 온라인 실행 JavaScript 및 콘솔 오류 없음');await browser.close();fs.writeFileSync(__dirname+'/verification.json',JSON.stringify({date:new Date().toISOString(),results,errors},null,2));console.log('ALL PASSED',results.length);
})().catch(e=>{fs.writeFileSync(__dirname+'/verification-failure.json',JSON.stringify({results,errors,failure:String(e),stack:e.stack},null,2));console.error(e);process.exit(1)});
function DesignBounds(f){const a=f.r*Math.PI/180;return {w:Math.abs(Math.cos(a))*f.w+Math.abs(Math.sin(a))*f.d,d:Math.abs(Math.sin(a))*f.w+Math.abs(Math.cos(a))*f.d};}
